### ISSUE TITLE
No Longer Able to Read State File

### ISSUE THREAD

**Issue by pfilbin90** [microsoft/azure-pipelines-extensions#1006]
Something happened within the last 24 hours to where my Azure DevOps terraform plan task can no longer load or read the statefile.  Apparently there is an extra command line argument now.

Was there a commit recently that could be causing this?

![image](https://user-images.githubusercontent.com/20479122/143071911-b9de459b-67c5-48fe-9f60-4711bfbb8373.png)

Update: Same thing happens with Terraform: Apply.   Terraform Init appears to work okay, but with Plan and Apply I end up with the following error:

`##[error]Error: Failed rmRF: EPERM: operation not permitted, unlink 'D:\a\r1\a\temp-output-9ff0c9db-acac-4a32-b1fc-fcf564b74476.json'`

**Comment by wdbetts** [comment]
Also seeing this error, same task ran successfully 12 hours ago. 

`task: TerraformTaskV2@2
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(Pipeline.Workspace)/terraform
        commandOptions: -out=plan -var-file=$(Pipeline.Workspace)/terraform/envvalues/GA/stag.tfvars
        environmentServiceNameAzureRM: redacted`

`Plan: 5 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: plan

To perform exactly these actions, run the following command to apply:
    terraform apply "plan"
C:\a\_tool\terraform\1.0.9\x64\terraform.exe version
Terraform v1.0.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.80.0
+ provider registry.terraform.io/hashicorp/helm v2.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1

Your version of Terraform is out of date! The latest version
is 1.0.11. You can update by downloading from https://www.terraform.io/downloads.html
##[error]Error: Failed rmRF: EPERM: operation not permitted, unlink 'C:\a\1\s\temp-plan-0c5d078f-ab26-4c11-95e1-e17ed0fb59cc.txt'`

**Comment by mericstam** [comment]
Update:  I could reproduce the error on windows agents.  I will revert the node upgrade for now.

**Comment by wdbetts** [comment]
Thank you @mericstam, I'll retest as soon as we see the version revert and confirm the fix.

**Comment by victor-chavez** [comment]
Same issue here task ran successfully before the Node 10 update. 

2021-11-23T19:50:45.5240377Z ------------------------------------------------------------------------
2021-11-23T19:50:45.5240703Z 
2021-11-23T19:50:45.5241130Z This plan was saved to: marketplace.tfplan
2021-11-23T19:50:45.5241484Z 
2021-11-23T19:50:45.5242457Z To perform exactly these actions, run the following command to apply:
2021-11-23T19:50:45.5243060Z     terraform apply "marketplace.tfplan"
2021-11-23T19:50:45.5243321Z 
2021-11-23T19:50:45.5586656Z [command]C:\hostedtoolcache\windows\terraform\0.12.9\x64\terraform.exe version
2021-11-23T19:50:46.2678579Z Terraform v0.12.9
2021-11-23T19:50:46.2679485Z + provider.azurerm v2.56.0
2021-11-23T19:50:46.2679965Z 
2021-11-23T19:50:46.2680615Z Your version of Terraform is out of date! The latest version
2021-11-23T19:50:46.2681392Z is 1.0.11. You can update by downloading from www.terraform.io/downloads.html
2021-11-23T19:51:03.4267542Z **##[error]Error: Failed rmRF: EPERM: operation not permitted, unlink 'D:\a\r1\a\temp-plan-1022a0c7-c7f7-4b54-bf16-0670d5c2447f.txt'**

**Comment by captainbrown** [comment]
Is there any way to lock in a release version?  I would love to do that as a workaround until the fix is released.

**Comment by mericstam** [comment]
I got a fix ready, Need to follow procedure to get it out. trying to get it out ASAP

**Comment by mericstam** [comment]
I did not revert node 10 but rather changed the way the temp files are removed

**Comment by victor-chavez** [comment]
After merged, who soon can be the fix publish?

**Comment by mericstam** [comment]
testing it now, if everything looks ok I will publish. so in 10-20 min approx.

**Comment by mericstam** [comment]
Just waiting for a final OK from my co-worker. so few more minutes.

**Comment by mericstam** [comment]
version 0.1.12 is published

**Comment by wdbetts** [comment]
![image](https://user-images.githubusercontent.com/719249/143131348-b6572331-b8c6-424e-9868-9cae60cca92b.png)
Got it! 

Plan step is green now, thank you!

**Comment by victor-chavez** [comment]
Thank so much for the quick response.

**Comment by devopsenggineer** [comment]
Hey guys, 

just checked below warning is no longer occurring anymore.  Thanks for the prompt response.

```
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

```
