### ISSUE TITLE
Provide TerraformTaskV2 plan output variable

### ISSUE THREAD

**Issue by JayDoubleu** [microsoft/azure-pipelines-extensions#1031]
It would be great if we would be able to capture the exit code of terraform plan from TerraformTaskV2 task.
This would be very useful in situations where we provide extra command argument `--detailed-exitcode`.
Based on exit code we would be able to conditionally enable apply stage/job/task if there are detected changes.

See: https://www.terraform.io/cli/commands/plan#detailed-exitcode 
Exit code: `2 = Succeeded with non-empty diff (changes present)`

**Comment by mericstam** [comment]
this is fixed in new repo. https://github.com/microsoft/azure-pipelines-terraform/pull/11
We will release it in a few days.
Open a new Issue in https://github.com/microsoft/azure-pipelines-terraform/issues if you feel it is incorrect
