### ISSUE TITLE
Release pipeline is failing with terraform project template for azure devops

### ISSUE THREAD

**Issue by soundd2** [microsoft/azure-pipelines-extensions#1047]
I have implemented Build pipeline and release pipeline using following lab link 
https://azuredevopslabs.com/labs/vstsextend/terraform/  However it is failing at the release pipeline due to the following error
![image](https://user-images.githubusercontent.com/94822959/166424010-1f193e91-6248-4091-b23d-b1eddb88aa19.png)
[](url)

and below is the error captured from  the logs:
m[31mError: [0m[0m[1mFailed to get existing workspaces: Error creating storage client for storage account "terraformstoraged7d37c12": azure: malformed storage account key: illegal base64 data at input byte 0[0m
Please assist.

**Comment by mericstam** [comment]
Hi, please use https://github.com/microsoft/azure-pipelines-terraform/issues for reporting issues for terraform
Br
Manuel
