### ISSUE TITLE
IIS Web App Deployment Using WinRM Version 1.6.4 Breaks MSDeploy Additional Arguments

### ISSUE THREAD

**Issue by cookontherun** [microsoft/azure-pipelines-extensions#1186]
Using TFS/DEVOPS and have multiple builds that stopped working yesterday after the IIS Web App Deployment Using WinRM extension update was pushed to our server. I don’t see a way to rollback this extension to the earlier version. The additional arguments feature of the build task does not pass the argument now to the MSDeploy command line: 

![image](https://github.com/microsoft/azure-pipelines-extensions/assets/16552210/bda7fa74-7c30-4fe9-b3b9-b529c81df901)

How can we get these -skip:file command line parameters to be included in the MsDeploy command line:

![image](https://github.com/microsoft/azure-pipelines-extensions/assets/16552210/9ed7e8ac-3a6c-44c4-83d6-7888c572fd68)

**Comment by Carlos-724** [comment]
Same issue.. it doesn't take into account "AdditionalArguments" parameter which is used to skip files or test the deployment with "-whatif". What a surprise today after the deployment ! 😃

**Comment by LeftTwixWand** [comment]
Hi @cookontherun and @Carlos-724 I apologize for the inconvenience.
I already work on the fix.

**Comment by LeftTwixWand** [comment]
@cookontherun can you please provide the task version, that you use.

**Comment by KevinCar98** [comment]
Hi @LeftTwixWand, I'm having the same issue on both versions: 2.1.3 and 1.5.3.

**Comment by LeftTwixWand** [comment]
Hey @cookontherun, @Carlos-724, @KevinCar98, @RicardoLans once again I apologize for the inconvenience.
We reverted all the changes made in 1.6.4 and will work on its improvement.
Not you can update `IIS Web App Deployment Using WinRM` to version 1.6.5 and keep working.

**Comment by LeftTwixWand** [comment]
Hey @RicardoLans @cookontherun @Carlos-724 @KevinCar98.
Today we released an updated version of IIS Web App Deployment extension with the fix of this issue.
Hope you won't have any issues with our extension in the future.
And thank you all for the feedback❤️
