### ISSUE TITLE
artifact-engine: unhandled rejection Error: certificate has expired

### ISSUE THREAD

**Issue by Werner-Calian** [microsoft/azure-pipelines-extensions#1212]
We've recently started getting failures in our release pipeline when using the External TFS Build artifact type to download the build artifiacts.

>Agent job
>7 error(s), 0 warning(s)
>Error: 	artifact-engine: unhandled rejection Error: certificate has expired 
>Error: 	Unhandled: certificate has expired 
>Error: 	Error: certificate has expired at Error (native) at TLSSocket.<anonymous> (_tls_wrap.js:1092:38) at emitNone (events.js:86:13) at TLSSocket.emit (events.js:185:7) at TLSSocket._finishInit (_tls_wrap.js:609:8) at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:439:38) 
>Error: 	Unhandled: certificate has expired 
>Error: 	Error: certificate has expired at Error (native) at TLSSocket.<anonymous> (_tls_wrap.js:1092:38) at emitNone (events.js:86:13) at TLSSocket.emit (events.js:185:7) at TLSSocket._finishInit (_tls_wrap.js:609:8) at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:439:38) 
>Error: 	artifact-engine: unhandled exception Error: certificate has expired 
>Error: 	Exit code 7 returned from process: file name 'C:\agents\3.232.0\externals\node\bin\node.exe', arguments '"D:\a\_tasks\DownloadExternalBuildArtifacts_b099689b-039e-4450-8658-c72e3895dd3f\15.232.0\download.js"'. 

It was still working on Saturday 9 December, but the last two days it just fails.

I've checked the token that we use for the service connection and it has not expired. The SSL certificate for our TFS server (TFS 2018 U2) has not expired either.

According to the Installed Extensions page in our Azure DevOps organization, the TFS artifacts for Release Management was updated to version 15.232.0 this past Monday (10 December).

What Am I missing? Which certificate has expired?

**Comment by v-mohithgc** [comment]
Hi @Werner-Calian , can you enable the debug logs (system.debug =true) and send us the failure and success logs to v-mohithgc@microsoft.com

**Comment by Werner-Calian** [comment]
Hi @v-mohithgc,

I've emailed the logs as requested. Thank you for helping.

**Comment by v-mohithgc** [comment]
> Hi @v-mohithgc,
> 
> I've emailed the logs as requested. Thank you for helping.

Hi, I haven't received any mail yet, can you please cross check?
id: v-mohithgc@microsoft.com

**Comment by Werner-Calian** [comment]
It definitely sent. No bounce-back email. I checked the address too. I zipped the logs together. Does your mail server perhaps block zip files?

**Comment by v-mohithgc** [comment]
> It definitely sent. No bounce-back email. I checked the address too. I zipped the logs together. Does your mail server perhaps block zip files?

I received it just now, thanks.
can you send previous success run logs as well?

**Comment by Werner-Calian** [comment]
Sent. I don't have previous run logs for that specific pipeline. I sent logs for another that is a copy of it.

We are experiencing the same issue on the deployment pipelines of another of our Azure DevOps organization (busy migrating Azure tenants).

**Comment by v-mohithgc** [comment]
@Werner-Calian I have reverted the recent changes and it's shipped with version 15.232.1, which should run fine.
can you please run and confirm back?

**Comment by Werner-Calian** [comment]
Will do. Just waiting for the extension to update on our DevOps org. Still listed as 15.232.1 on the market place

**Comment by v-mohithgc** [comment]
> Will do. Just waiting for the extension to update on our DevOps org. Still listed as 15.232.1 on the market place

Sure, but I guess the once you run the pipeline, it will auto pick the latest version directly. No need to change anything manually from org settings

**Comment by v-mohithgc** [comment]
Thanks for confirming.
