### ISSUE TITLE
Override parameters using SetParameters.xml (&quot changing as &amp;quot;)

### ISSUE THREAD

**Issue by hotamkushwah** [microsoft/azure-pipelines-extensions#192]
I am using Override parameter to override my connection strings.Task is working fine but it is changing &quot to &amp;quot .
For example : This is the connection string 
connection string=&quot;data source=source;initial catalog=test;...
And I am changing it to as below using Override parameter.
connection string=&quot;data source=Othersource;initial catalog=test;...

In this case I am getting as below : 
connection string=&amp;quot;data source=Othersource;initial catalog=test;...

It is working correctly when I run MSdeploy through command line.

**Comment by mvvsubbu** [comment]
Can you share full logs with system.debug

**Comment by merrellsj** [comment]
Somewhat similar issue. When I try to use the override parameters I get the error System.Exception: Error: Unrecognized argument 'Web'. All arguments must begin with "-". I am entering them into the release configuration as name="settingName",value="settingValue" I've also tried settingName=settingValue both result in the same error. Any ideas?

**Comment by vincentdass** [comment]
Closing the issue, as there is no response. 
Please feel free to reopen / open a new thread, if the issue still persists.
