### ISSUE TITLE
Deployement failed due to error "File in use"

### ISSUE THREAD

**Issue by cedricvig** [microsoft/azure-pipelines-extensions#235]
Frequently the "WinRM: IIS Web App Deployment" task failed with the error "File in use".
The only workaround I know is to manually stop the pool of the site deploying.

Is the  "WinRM: IIS Web App Deployment" task can stop the pool before trying to deploy ?

**Comment by niadak** [comment]
@cedricvig , Can you please add 'WinRM - IIS Web App Management' task to stop the pool before "WinRM: IIS Web App Deployment"  task?

**Comment by cedricvig** [comment]
Hi, I already use   'WinRM - IIS Web App Management' task before. Do I have to add an Additional AppCmd.exe Commands to stop the pool ?

**Comment by rajatagrawal-dev** [comment]
I think you should 2 new 'WinRM - IIS Web App Management' tasks - one before the "WinRM: IIS Web App Deployment" task and one after it. You should set up the the first manage task to stop the web app, and set the second manage task to start the web app. You can refer to [this link](https://technet.microsoft.com/en-us/library/cc732742(v=ws.10).aspx) that specifies the AppCmd arguments to accomplish this.

**Comment by vincentdass** [comment]
Closing the issue, as there is no response. 
Please feel free to reopen / open a new thread, if the issue still persists.
