### ISSUE TITLE
IISWebAppMgmt: Type Error in Add-SslCert

### ISSUE THREAD

**Issue by zivillian** [microsoft/azure-pipelines-extensions#281]
The IISVersion is read from Registry as number, but converted to string in [Add-SslCert](https://github.com/Microsoft/vsts-rm-extensions/blob/528c04c13dd85314561412329dc83bfb28b0b6a1/Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppMgmt/AppCmdOnTargetMachines.ps1#L186) `[string]$iisVersion`, thus the [comparison](https://github.com/Microsoft/vsts-rm-extensions/blob/528c04c13dd85314561412329dc83bfb28b0b6a1/Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppMgmt/AppCmdOnTargetMachines.ps1#L206) `$iisVersion -ge 8` fails for IIS >= 10.

We found this, while trying to deploy 2 different websites to a shared host with Server 2016 both using ssl on port 443 with SNI enabled. The second deployment fails with 

> SSL Certificate add failed, Error: 183 Cannot create a file when that file already exists.

because the task tries to add a second cert using ipport instead of hostnameport.

**Comment by 616b2f** [comment]
Same issue here.

**Comment by niadak** [comment]
Thanks for reporting the issue. We will fix the bug. Please feel free to send a PR with the fix and contribute to this repo if possible.

**Comment by Toukiletoukan** [comment]
Hi, any update on this issue ?
Thanks !

**Comment by mmajcica** [comment]
Same here. Any idea when and if the proposed fix will become part of a release?

**Comment by MarcoWesterink** [comment]
Any progress? Same here after multiple successful deployments it suddenly decided to throw this error.

**Comment by marcelocelo** [comment]
This is not a bug, at least in my version. When configuring the bindings, there is a "Server Name Indication required" option. By checking this option, it will use hostname and not ip when adding the certificate. That solved the problem for me.

**Comment by basroovers** [comment]
I still have this issue with SNI enabled. Why was my change not approved?

**Comment by Ajay-MS** [comment]
@basroovers  I approved the PR. I have few ask can you please resolve them in PR.

**Comment by Ajay-MS** [comment]
@basroovers 
Also, I observed that issue has been fixed in version 2.* of the task already. 

[Code Reference - IISWebAppMgmt V2](https://github.com/microsoft/azure-pipelines-extensions/blob/a12d0f890b9c85a3252e315b74a554e3f41b75c6/Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppMgmt/IISWebAppMgmtV2/AppCmdOnTargetMachines.ps1)

Can you please try with version 2.* of the task.

**Comment by basroovers** [comment]
@Ajay-MS I can't use version 2.* of the task. Only version 0.* is available for deployment groups.

**Comment by nadcraker** [comment]
I am having this issue as well. How can you deploy to just a single target? All I can select are deployment groups, which means all I can use is verison 0.* of this task.

**Comment by phalecsjagboro** [comment]
Is there any chance this will be fixed, This is still a pain for me as we speak.

**Comment by kmkumaran** [comment]
@nadesu , @chshrikh for follow up

**Comment by andyong79** [comment]
I was getting this too using an IIS Web App Manage task in my Azure Devops release pipeline in classic mode. I setup binding to use the SSL certificate thumbprint and enabled SNI. First deploy works fine but 2nd and subsequent attempts (after the binding exists) kept resulting in this error. In the end I just added a powershell task with an inline script to delete the binding first so it can be readded again by the IIS Web App Manage task. You could add a check if exists in the powershell script but for now I just set the powershell script to continue on error (if the binding doesn't exist)
# Cleanup existing ssl binding so it can be readded
netsh http delete sslcert hostnameport=$(hostName):443

**Comment by amit-avit** [comment]
@chshrikh @AmrutaKawade

**Comment by huysentruitw** [comment]
Can this issue be re-opened? I had exactly the same issue as @andyong79 describes.

**Comment by benjaminadrom** [comment]
why does a "release" even try to add a cert in first place? or do i get that wrong?
