### ISSUE TITLE
Upgrade to Microsoft.Azure.Servicebus 2.0. 

### ISSUE THREAD

**Issue by paulgmiller** [microsoft/azure-pipelines-extensions#304]
the current service bus package uses a custom  amqp prot which is blocked in some environments. Microsoft.Azure.ServiceBus 2.0.0 allows you to tunnel over 443 web sockets. Might be helpful if people are stuck in the future.

//on service fabric can't poll service bus on port 5671 so tunnel over 443.
            //https://stackoverflow.com/questions/32045375/how-to-use-amqp-1-0-with-the-service-bus-net-api-azure
            //https://github.com/Azure/azure-service-bus-dotnet/blob/9b31751a1c5ade61f353bd4905b0665ad0269dfa/src/Microsoft.Azure.ServiceBus/TransportType.cs
            if (!taggerConnectionString.Contains("TransportType=AmqpWebSockets"))
            {
                taggerConnectionString += ";TransportType=AmqpWebSockets";
            }

**Comment by niadak** [comment]
@paulgmiller , I dont see any usage of the Azure ServiceBus in this repo. Why this is relevant here?  Am I missing anything here?

**Comment by niadak** [comment]
OK. I guess we have dependency on this in https://github.com/Microsoft/vsts-rm-extensions/blob/master/TaskBroker/VstsServerTaskBroker.Azure/ServiceBus.

We will investigate and get back.

**Comment by rohit-batra** [comment]
We have started using [Service bus 2.0](https://github.com/microsoft/azure-pipelines-extensions/blob/0eeec9e3db25f5e0c6b8102feeeac023e2db09bd/ServerTaskHelper/ServiceBusMessageHandler/ServiceBusMessageHandler.csproj#L11)

Service bus message Handler feed can be found [here](https://1essharedassets.visualstudio.com/1esPkgs/_packaging?_a=package&feed=vsts_rm_extensions&package=ServiceBusMessageHandler&protocolType=NuGet&version=0.1.0-CI-20190527-074755)
