### ISSUE TITLE
Error at Deploy IIS Task in Release Definition on VSTS

### ISSUE THREAD

**Issue by vinaysandela** [microsoft/azure-pipelines-extensions#404]

**Comment by SumiranAgg** [comment]
@vinaysandela Sorry fro late reply. Your target machine might not be winrm enabled.
Can you verify by running following script on local:

$soptions = New-PSSessionOption -SkipCACheck
$cred = Get-Credential
$computername = <EnterComputerName>
$computerport = <EnterPort>
Enter-PSSession -ComputerName $computername -Port $computerport -Credential $cred -SessionOption $soptions -UseSSL

Substitute values as required. If this didnt work you will have to configure winrm on target machine. For this run script below ontarget machine:
https://github.com/Microsoft/vsts-rm-documentation/blob/master/WinRM/WinRM-Http-Https-Without-Makecert/ConfigureWinRM.ps1
