### ISSUE TITLE
SonarScanner for MSBuild - A multi-project can't have source folder.

### ISSUE THREAD

**Issue by jigneshc** [microsoft/azure-pipelines-extensions#437]
I am trying to scan multi-project (C# MVC project) using SonarScanner for MSBuild and I am  getting below warning.

Warning - A multi-module project can't have source folders, so 'Some directory....\Folder Name' won't be used for the analysis. If you want to analyse files of this folder, you should create another sub-module and move them inside it.

I am using SonarQube 5.6.6 and it has Sonar C# Analyzer 6.6.
Since this analyzer requires SonarScanner for MSBuild to scan project it does not support sonar.properties file, so is there any way to create sub-module like we are able to create using sonar scanner. Below is the image :
![5](https://user-images.githubusercontent.com/26161707/40764637-70ce9e7a-64c7-11e8-9512-8c2df96737d6.PNG)

**Comment by kmkumaran** [comment]
@jigneshc - Can you tell us which task in this extension repo you are using to see the above behavior?
