### ISSUE TITLE
unable to target specific app pool

### ISSUE THREAD

**Issue by gforceg** [microsoft/azure-pipelines-extensions#471]
I am using the Manage IIS App Management task to create an app pool w/ a custom identity. This seems to be working and creates a new app pool if one does not exist in the deployment environment.

My application is deployed to a virtual path and should have the site path "Default Web Site/$(MyProjectName)". When I use the IIS Web Deployment task, I am unable to specify my app pool.

I tried using various key value pairs under the 'override parameters' input but nothing seems to take.

**Comment by rajatagrawal-dev** [comment]
@gforceg Application pool should be automatically detected. You need to first use IIS Manage task to create a website in your application pool. Then you can deploy to that website using the IIS Deploy task.

**Comment by gforceg** [comment]
In my situation there is a website 'Default Web Site' that already exists. All applications use the website: 'Default Web Site/$(MyProjectName)'. We host many apps on the same IIS server and use the convention: http://<servername>/appname.

Is our setup incompatible with the VSTS tasks?

**Comment by Ajay-MS** [comment]
Instead of the website deployment above operation is being supported at management task.

You have to do following steps in IIS Manage task:
- create $(MyProjectName) virtual path as a virtual application 
- In virtual application you can specify the app pool
