### ISSUE TITLE
IIS Manage fails to check if vdir already excists

### ISSUE THREAD

**Issue by allisonjaneklok** [microsoft/azure-pipelines-extensions#533]
Upon running the cmd ".\appcmd list vdir **-**vdir.name:"{VDIR_NAME}"", powershell returns an error. Which is registered in the script as "VDIR not found". Incorrectly, as is might exist. The task should be \appcmd list vdir **/**vdir.name:"{VDIR_NAME}"

Please can you fix this problem? I've seen it in AppCmdOnTargetMachines.ps1 (line 598)

Thnx!

**Comment by Ajay-MS** [comment]
@allisonjaneklok 

Input expects virtual directory name should start with a "/". 

Here are snippet from task logs :
```
2019-05-14T06:11:54.1586889Z "C:\WINDOWS\system32\inetsrv\appcmd.exe"  list vdir -vdir.name:"MySampleApp/virDirPath1"
2019-05-14T06:11:54.1728385Z VERBOSE: virtualDirectory = VDIR "MySampleApp/virDirPath1" (physicalPath:C:\inetpub\wwwroot)
2019-05-14T06:11:54.1870004Z VERBOSE: Virtual Directory ("MySampleApp/virDirPath1") already exists
```

Please let me know if I am missing something here.  Also, it will be great if you could share complete debug logs which will give more insight to the problem. 

Debug logs you can enable by adding a release variable `system.debug` with value `true`.

**Comment by Ajay-MS** [comment]
Closing as no repro. Feel free to reopen with debug logs.
