### ISSUE TITLE
The task does not carry an implementation that is compatible with your current operating system

### ISSUE THREAD

**Issue by FrancisFYK** [Microsoft/azure-pipelines-extensions#538]
A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X86)'. Contact the task author for more details.

I'm using one windows server 2012 datacenter 64 system

**Comment by toddca** [comment]
I am receiving this now too. The task version is 1.3.9, I am using onPrem Win 2016 domain-joined agent/machines and this all use to work. I setup a new release and now things are no longer working.

**Comment by chshrikh** [comment]
the current design of task only works with x64 operating system and x64 version of agent. Ensure to use x64 version of agent, instead of x86.

**Comment by waheedsayed** [comment]
I found what was my problem. I installed x86 version of the agent by mistake, this is why it was reporting that `Agent.OSArchitecture` =  X86. Build is working again after installing the x64 version.

**Comment by toddca** [comment]
Yep installing the x64 agent resolved my issue too.
