### ISSUE TITLE
IIS Web App Management Version 2 does not properly apply the password of a custom account to the application pool

### ISSUE THREAD

**Issue by usrabusr** [microsoft/azure-pipelines-extensions#541]
I am consistently having an issue with IIS Web App Management (**Version 2**) does not properly apply the password of a custom account to the application pool.  I am able to do this with **Version 1** task without an issue.

**Comment by devingoble** [comment]
I had this same issue. I disabled the task and then created a new one. The new one worked fine.

**Comment by Ajay-MS** [comment]
We are unable to repro this issue. Closing this issue. Please share debug logs if you are still facing this issue. 

Debug logs can be enabled by adding release variable `system.debug` with value `true`.

**Comment by GregoryOtt** [comment]
@Ajay-MS => I'm able to reproduce this error with a password with a `$` character.

**Comment by Ajay-MS** [comment]
@GregoryOtt Thanks for sharing the scenario. I will try it out and will update the thread.

**Comment by RoshanKumarMicrosoft** [comment]
@rajatagrawal-dev  Can you please look into this issue

**Comment by chperich** [comment]
This is a known issue. Fix for this is currently in [PR](https://github.com/microsoft/azure-pipelines-extensions/pull/720) and will roll out in a couple of weeks. Until then you can try and escape the dollar character by changing "$" to "`$"
