### ISSUE TITLE
Feature Request: Upload Artifacts to Anaconda Cloud

### ISSUE THREAD

**Issue by peterjc123** [Microsoft/azure-pipelines-extensions#548]
Anaconda Cloud is widely used to manage the Python environments. There is already an authentication service endpoint for pip, so I think it is necessary to create one for conda. The upload script is actually very simple to write. 
```bat
:: USERNAME and PASSWORD should be saved in the service connection.
:: PACKAGE should be passed from the task definition.
echo yes | anaconda login --username %USERNAME% --password %PASSWORD%
anaconda upload %PACKAGE%
```
I want this to be implemented because, in that way, we can reuse the credentials of Anaconda Cloud between different build definitions. Otherwise, we will have to set these variables multiple times.

**Comment by omeshp** [comment]
@peterjc123 I should be fairly easy to add it as custom task, have a look at https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops or you can raise a request at https://github.com/Microsoft/azure-pipelines-tasks repo.

**Comment by peterjc123** [comment]
@omeshp Thanks for your answer. I'll post it in the azure-pipelines-tasks repo.
