### ISSUE TITLE
Service endpoint URL not displaying on TFS 2018 update 2

### ISSUE THREAD

**Issue by jsalado** [microsoft/azure-pipelines-extensions#558]
Hello,

I have a working extension published in the marketplace: [Kiuwan extension](https://marketplace.visualstudio.com/items?itemName=kiuwan-publisher.kiuwan-analysis-extension)

It has a service endpoint contribution defined like this:
`        {
            "id": "kiuwan-service-endpoint",
            "description": "Kiuwan servide endpoint to connect to the Kiuwan platform",
            "type": "ms.vss-endpoint.service-endpoint-type",
            "targets": [
                "ms.vss-endpoint.endpoint-types"
            ],
            "properties": {
                "name": "kiuwan",
                "displayName": "Kiuwan Platform",
                "url": {
                    "displayName": "Kiuwan URL",
                    "value": "https://www.kiuwan.com/",
                    "isVisible": true,
                    "helpText": "For the cloud Kiuwan Service use: https://www.kiuwan.com This is the default.</br>For Kiuwan Enterprise on-premises use your Kiuwan server URL (i.e. http://kiuwan.mycompany.com)."
                },
                "dataSources": [
                    {
                        "name": "TestConnection",
                        "endpointUrl": "{{endpoint.url}}saas/rest/v1/info",
                        "resultSelector": "jsonpath:$.username"
                    },
                    {
                        "name": "ListApplications",
                        "endpointUrl": "{{endpoint.url}}saas/rest/v1/apps/list",
                        "resultSelector": "jsonpath:$[*].name"
                    }
                ],
                "authenticationSchemes": [
                    {
                        "type": "ms.vss-endpoint.endpoint-auth-scheme-basic",
                        "inputDescriptors": [
                            {
                                "id": "username",
                                "name": "Username",
                                "description": "This is your Kiuwan username",
                                "inputMode": "textbox",
                                "isConfidential": false,
                                "validation": {
                                    "isrequired": true,
                                    "dataType": "string"
                                }
                            },
                            {
                                "id": "password",
                                "name": "Password",
                                "description": "Yup! this is your Kiuwan password",
                                "inputMode": "passwordBox",
                                "isConfidential": true,
                                "validation": {
                                    "isrequired": true,
                                    "dataType": "string"
                                }
                            }
                        ]
                    }
                ],
                "helpMarkdown": "<a href=\"https://www.kiuwam.com\" target=\"_blank\"><b>Learn More</b></a>"
            }
        }
`

Installing the latest extension version (2.3.2) on TFS 2017 updates 2 and 3 or in Azure DevOps in the cloud, when adding a service connection to the Kiuwan platform the Kiuwan URL is visible and can be changed accordingly but for TFS 2018 update 2, the Kiuwan URL is not visible and cannot be changed if needed.

Is there anything I'm missing?

**Comment by jsalado** [comment]
My endpoint URL is defined as explained in [this document](https://github.com/Microsoft/azure-pipelines-extensions/blob/master/docs/authoring/endpoints/serviceEndpoints.md#customizeurl)

**Comment by jsalado** [comment]
I've tried the same on TFS 2015 update 3 and it doesn't display either.

Inspecting the page with chrome dev tools I see that the <tr> html element is there:
`<tr data-bind="css: { 'endpoint-hidden-column': !showUrl() }" class="endpoint-hidden-column">
                    <td>
                        <label for="url" data-bind="css: { 'bold-text': isUrlInvalid() }, text: serverUrlDisplayName" class="">Kiuwan URL</label>
                    </td>
                    <td class="serverUrl">
                        <input class="textbox" data-bind="value: serverUrl, valueUpdate: ['blur', 'afterkeydown'], css: { 'invalid': isUrlInvalid() }" required="" autofocus="" id="url" type="text">
                    </td>
                    
                        <td data-bind="showTooltip: { text: serverUrlHelpText, pivotSiblingCssClass: 'serverUrl' }"><span class="help icon icon-info-white"></span><div class="taskeditor-help-tooltip"><span class="close icon icon-close-small"></span><div class="content">For the cloud Kiuwan Service use: https://www.kiuwan.com This is the default.<br>For Kiuwan Enterprise on-premises use your Kiuwan server URL (i.e. http://kiuwan.mycompany.com).</div></div></td>
                    
                </tr>`

 but it renders with this style:
`.endpoint-hidden-column {
    display: none;
}`

Toggling that style on/off with the dev tools I get the element to display. Why is it not displaying by default if the isVisible property is set to true, and why only for these 2 versions TFS 2018 update 2 and TFS 2015 update 2?

Guessing that it has something to do with the behavior of the showUrl() function...

**Comment by jsalado** [comment]
Hello there,

I dag deeper on this issue and found a way to make it work with a minor side effect though.

It seems that the isVisible property is not taken into account in some TFS versions.

It seems that the visibility of the url field in the service endpoint definition is controlled by the value field. If a default value is specified the url field is hidden regardless of the isVisible property in TFS 2018 and 2015. If value is not specified then the url field is shown and can be changed in all versions and platforms. The side effect is that I cannot specify a default value to appear in the url field...

So the service endpoint url definition that worked for me on all versions is the following:
`                "url": {
                    "displayName": "Kiuwan URL",
                    "helpText": "For the cloud Kiuwan Service use: https://www.kiuwan.com This is the default.</br>For Kiuwan Enterprise on-premises use your Kiuwan server URL (i.e. http://kiuwan.mycompany.com)."
                }
`
I still consider this a bug mostly because the behavior is different to what is documented and I think that if the isVisible property exists it should be taken into account, it does offers more flexibility.

**Comment by omeshp** [comment]
@jsalado We have verified that this issue is fixed with TFS 2019 release. It won't be possible to back port the fix though, so you will need to use the workaround if you want to support older TFS releases.
