### ISSUE TITLE
Stopping an application pool that is already stopped causes an error

### ISSUE THREAD

**Issue by devingoble** [microsoft/azure-pipelines-extensions#573]
It would be nice if the App Management task could determine the status of an app pool before it tries to start or stop it. The reason is that it tends to cause errors if the state isn't what it expects to see. This causes issues if you are trying to act on errors.

**Comment by Ajay-MS** [comment]
PR - https://github.com/microsoft/azure-pipelines-extensions/pull/615

**Comment by Ajay-MS** [comment]
Closing this issue as PR merged.
