### ISSUE TITLE
Teamcity artifact URL's is not URL encoded when downloading

### ISSUE THREAD

**Issue by michaelthyregod** [Microsoft/azure-pipelines-extensions#581]
When downloading from teamcity, the URL for the artifact does not seem to be URL encoded resulting in problems if there is special characters in the artifact filename.

Example : I have an artifact named something like this "*/[SOMENAME][SOME OTHER NAME]Some name"

The brackets in the filename is valid in most OS's, but somehow it is not valid when being downloaded from TC, and reports "java.lang.IllegalArgumentException: Illegal character in path" in the response from Teamcity.

Please fix.

**Comment by gykuma** [comment]
Hi @michaelthyregod 
I tried out the task for downloading artifacts having brackets in path, and it seems to work fine for me. I have added the logs below. Please let me know if I'm missing out something.

![image](https://user-images.githubusercontent.com/33627957/54255928-0c89d200-4580-11e9-84c5-bc9792811107.png)

If you are still facing the issue please set `System.Debug` to `true` in release variables and share the new release logs. Also share the TeamCity version.

You can share the details to RM_Customer_Queries@microsoft.com

**Comment by gykuma** [comment]
@michaelthyregod I'm closing this issue for now. Please feel free to reopen in case you are still facing the issue.
