### ISSUE TITLE
DistributedTask.ServerTask.Remote.Common nuget package has not been updated with the latest commits from master

### ISSUE THREAD

**Issue by garretmagin** [microsoft/azure-pipelines-extensions#594]
It looks like the feed only contains an old version of the nuget package for DistributedTask.ServerTask.Remote.Common. It is missing the commit from PR #580 merged to master ~23 days ago that adds support for setting task variables.

**Comment by rohit-batra** [comment]
Hello @garretmagin , 
we have updated the feed with the latest package. Can you please try it out and let us know if it works for you ?

Thanks 
Rohit

**Comment by garretmagin** [comment]
At this point I have forked the code in my repo and no longer need the nuget package as it is undergoing some refactoring.
