### ISSUE TITLE
Release deployment fails: ArtifactEngine.js unhandled rejection due to "read ECONNRESET"

### ISSUE THREAD

**Issue by EdmundoMartinez** [Microsoft/azure-pipelines-extensions#597]
This error occurs when running the Azure Dev Ops release built-in Download Artifacts from a build pipeline, artifactEngine.js throws undhandled rejection due to "read ECONNRESET".

There is no information in the regular logs if there was a retry or not to handle this problem.

We have hundreds of release executions and most of them succeed; but in this particular case the engine threw the exception.

I'm logging the issue here, since this project owns the [artifactEngine.js](https://github.com/Microsoft/azure-pipelines-extensions/blob/master/Extensions/ArtifactEngine/Engine/artifactEngine.ts) file.

Here's the output of the task execution:

```
##[section] Starting: Download artifact - BuildDefinitionName removed
==============================================================================
Task         : Download Build Artifacts
Description  : Download Build Artifacts
Version      : 0.148.0
Author       : Microsoft Corporation
Help         : 
==============================================================================
_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.148.0\node_modules\artifact-engine\Engine\artifactEngine.js:157
    throw err;
    ^


Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TLSWrap.onread (net.js:568:26)
##[error]artifact-engine: unhandled rejection Error: read ECONNRESET
##[error]Unhandled: read ECONNRESET
##[error]Unhandled: read ECONNRESET
##[error]artifact-engine: unhandled exception Error: read ECONNRESET
##[error]Exit code 7 returned from process: file name 'externals\node\bin\node.exe', arguments '"_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.148.0\main.js"'.
```

**Comment by gykuma** [comment]
@EdmundoMartinez Thanks for reporting the issue.

We recently released a hotfix for the task (0.148.1) for fixing this issue. Please let us know if the issue still exists for you.

**Comment by EdmundoMartinez** [comment]
Thanks @gykuma, I can see our Azure Dev Ops is now using version 0.148.1 of the task.

**Comment by EdmundoMartinez** [comment]
This problem is not reproducing anymore.
Closing the issue for now.
