### ISSUE TITLE
error trying to validate the endpoint definition when publishing an extension. 

### ISSUE THREAD

**Issue by garthbf** [microsoft/azure-pipelines-extensions#608]
I have an extensions that I had to make minor changes to the code. it published successfully over a year ago. now it will not publish. 
the error is:
error: Unable to parse the service connection contribution. Parsing failed with the following error: Error converting value "@{type=ms.vss-endpoint.endpoint-auth-scheme-basic; inputDescriptors=System.Object[]}" to type \'Microsoft.VisualStudio.Services.ServiceEndpoints.WebApi.ServiceEndpointAuthenticationScheme\'. Path \'authenticationSchemes[0]\'.',
the json has not changed other then changing the categories to "Azure Pipelines" from "Build / Release"
here is the json:

"contributions": [
    {
      "id": "servicenow-change-request",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "buildtask"
      }
    },
    {
      "id": "servicenow-endpoint",
      "description": "Service Endpoint type for ServiceNow Connections",
      "type": "ms.vss-endpoint.service-endpoint-type",
      "targets": [ "ms.vss-endpoint.endpoint-types" ],
      "properties": {
        "name": "servicenow",
        "displayName": "ServiceNow",
        "icon": "images/extension-icon.png",
        "url": {
          "displayName": "Server Url",
          "helpText": "Url for the ServiceNow Server to connect to."
        },
        "authenticationSchemes": [
          {
            "type": "ms.vss-endpoint.endpoint-auth-scheme-basic",
            "inputDescriptors": [
              {
                "id": "username",
                "name": "User name",
                "description": "User Name in ServiceNow.",
                "inputMode": "textbox",
                "isConfidential": false,
                "validation": {
                  "isRequired": true,
                  "dataType": "string",
                  "maxLength": 300
                }
              },
              {
                "id": "password",
                "name": "Password",
                "description": "Password",
                "inputMode": "passwordbox",
                "isConfidential": true,
                "validation": {
                  "isRequired": true,
                  "dataType": "string",
                  "maxLength": 300
                }
              }
            ]
          }
        ],
        "helpMarkDown": ""
      }

**Comment by garthbf** [comment]
help, still waiting for help on this.

**Comment by omeshp** [comment]
@garthbf I tried the below endpoint contribution locally and it seems to be working fine. Can you validated the syntax is correct, if you are still facing the issue can you share the extension json which is giving the error?
```
    {
      "id": "servicenow-endpoint",
      "description": "Service Endpoint type for ServiceNow Connections",
      "type": "ms.vss-endpoint.service-endpoint-type",
      "targets": [
        "ms.vss-endpoint.endpoint-types"
      ],
      "properties": {
        "name": "servicenow",
        "displayName": "ServiceNow",
        "icon": "images/extension-icon.png",
        "url": {
          "displayName": "Server Url",
          "helpText": "Url for the ServiceNow Server to connect to."
        },
        "authenticationSchemes": [
          {
            "type": "ms.vss-endpoint.endpoint-auth-scheme-basic",
            "inputDescriptors": [
              {
                "id": "username",
                "name": "User name",
                "description": "User Name in ServiceNow.",
                "inputMode": "textbox",
                "isConfidential": false,
                "validation": {
                  "isRequired": true,
                  "dataType": "string",
                  "maxLength": 300
                }
              },
              {
                "id": "password",
                "name": "Password",
                "description": "Password",
                "inputMode": "passwordbox",
                "isConfidential": true,
                "validation": {
                  "isRequired": true,
                  "dataType": "string",
                  "maxLength": 300
                }
              }
            ]
          }
        ]
      }
    }
```

**Comment by Lovakumar** [comment]
Closing this issue as we don't have enough data to investigate this further. Re-open the issue with details if it is still an issue.
