### ISSUE TITLE
'IIS Web App Manage' fails when changing SSL Thumb print

### ISSUE THREAD

**Issue by PoulNielsen** [microsoft/azure-pipelines-extensions#623]
In TFS 2018 update 3, The task 'IIS Web App Manage' (version 0.5.5) fails when changing the SSL Thumb for a web site (using HTTPS and SNI).

It fails with :
  SSL Certificate add failed, Error: 183
  Cannot create a file when that file already exists.

**Comment by 20shivangi** [comment]
@PoulNielsen 
Can you share the debug log with us? Set the system.debug to true and create a new release.

**Comment by vincentdass** [comment]
Closing the issue as there is no response.
Please feel free to reopen/ start a new thread.
