### ISSUE TITLE
Passing headers to getTokenUsingBasicAuth 

### ISSUE THREAD

**Issue by pinkfloydx33** [microsoft/azure-pipelines-extensions#630]
I'm currently using `#getTokenUsingBasicAuth` in my service connection to pass basic authentication through to retrieve a token that the actual service connection can use. Due to a change outside of my control, I now need to include a specific header in that request.

Does this function (`getTokenUsingBasicAuth`) accept a parameter for headers? If so, what format should it be in? I assume one of the following:

`headers: { 'my-header': 'header-value' }` or
`headers: [ {name:'my-header', value: 'header-value'} ]`

If this function does _not_ allow for this, is there any chance it will be added in, or at the very least use the headers defined on the authentication scheme itself?

**Comment by Lovakumar** [comment]
You can use getTokenUsingBasicAuth function in both headers and authorizationHeaders. Sample code below:

"authenticationSchemes": [
          {
            "type": "ms.vss-endpoint.endpoint-auth-scheme-basic",
            "**headers**": [{"name": "Jenkins-Crumb", "value": "{{#equals request.Method 'POST' 1}}{{ #getTokenUsingBasicAuth  { 'username' : 'endpoint.username', 'password' : 'endpoint.password', 'resultSelector' : 'jsonpath:$.crumb', 'method':'get', ignoreError:'true', 'authServerUrl':'endpoint.url\/crumbIssuer\/api\/json\/' } }}{{/equals}}"}]
          }
        ]

**Comment by pinkfloydx33** [comment]
Thanks, but that's not quite what I meant. Consider this as my _current_ implementation:

```json
{  
   "id":"my-endpoint-type",
   "description":"Service Endpoint for connections to MyService",
   "type":"ms.vss-endpoint.service-endpoint-type",
   "targets":[  
      "ms.vss-endpoint.endpoint-types"
   ],
   "properties":{  
      "name":"myservice",
      "displayName":"MyServiceType",
      "url":{   "displayName":"Url", "helpText":"The URL" },      
      "authenticationSchemes":[  
         {  
            "type":"ms.vss-endpoint.endpoint-auth-scheme-basic",
            "headers":[  
               {  
                  "name":"Authorization",
                  "value":"Bearer {{ #getTokenUsingBasicAuth { 'username' : 'endpoint.username', 'password' : 'endpoint.password', 'resultSelector' : 'jsonpath:$.access_token', 'method':'post', 'authServerUrl':'endpoint.url/token', 'body' : {'username' : 'endpoint.username', 'password' : 'endpoint.password'} } }}"
               }
            ],
            "inputDescriptors":[  
               {  
                  "id":"username",
                  "name":"UserName",
                  "description":"User Name",
                  "inputMode":"textbox",
                  "isConfidential":false,
                  "validation":{  "isRequired":true, "dataType":"string" }
               },
               {  
                  "id":"password",
                  "name":"Password",
                  "description":"Password",
                  "inputMode":"passwordbox",
                  "isConfidential":true,
                  "validation":{  "isRequired":true, "dataType":"string" }
               },
               {  
                  "id":"environmentId",
                  "name":"environment",
                  "description":"",
                  "inputMode":"textbox",
                  "isConfidential":false,
                  "validation":{  "isRequired":true, "dataType":"string" }
               }
            ]
         }
      ]
   }
},
```

I would _like_ to change it to something similar to the following (truncated a bit for brevity):

```json
"authenticationSchemes":[  
     {  
        "type":"ms.vss-endpoint.endpoint-auth-scheme-basic",
        "headers":[  
           {  
              "name":"Authorization",
              "value":"Bearer {{ #getTokenUsingBasicAuth { 'username' : 'endpoint.username', 'password' : 'endpoint.password', 'resultSelector' : 'jsonpath:$.access_token', 'method':'post', 'authServerUrl':'endpoint.url/token', 'body' : {'username' : 'endpoint.username', 'password' : 'endpoint.password'}, 'headers': [{'name':'X-Something-Special','value':'endpoint.environmentId'}] } }}"
           },
           {
              "name":"X-Something-Special",
              "value":"{{{ endpoint.environmentId }}}"
           }		   
        ],
        "inputDescriptors":[  ...  ]
     }
]
```

Notice that I've added a header (`X-Something-Special`) in **two** places. The first is part of the Authentication Scheme itself (after the Authorization Header) which _should_ work fine. But I need to include this header on **all** requests, including the one that is made via the function `getTokenUsingBasicAuth` to endpoint.url/token. In my sample above I've added a new property to the method call arguments to that function (`headers`) however I'm not sure if it will actually be used by the function, nor if I am specifying it correctly. Here's just the method call I'm attempting (in quotes so I could bold the addition I'm attempting to make)

> Bearer {{ #getTokenUsingBasicAuth { 
>     'username' : 'endpoint.username', 
>     'password' : 'endpoint.password', 
>     'resultSelector' : 'jsonpath:$.access_token',
>     'method':'post', 
>     'authServerUrl':'endpoint.url/token',
>     'body' : {'username' : 'endpoint.username', 'password' : 'endpoint.password'},
>     **'headers': [{'name':'X-Something-Special','value':'endpoint.environmentId'}]**
>  } }}


We recently (and unexpectedly in a hurry) migrated from on-prem Azure DevOps Server into hosted Azure DevOps Services. This has caused an issue with our service connections. Unfortunately I can't just "try it out" because I'm waiting for some firewall rules to be fixed and the generation of a new URL. Even once those are in place, there's a new requirement imposed on me which requires I add this header on all external requests. If I can't include the header in both requests (for the token and "normal" endpoint usage) I'll have to look into what other alternatives exist. 

Since I can't currently test it out, I'm trying to determine if it's even even possible so that we know sooner than latter if we have to design some sort of new solution. Unfortunately there's no (public) documentation of this function #451  so I need to ask directly.

In the interim I've actually tried it both ways as well as with some typos in the names to see if it would at the very least break the Azure DevOps UI (by watching the network requests in Chrome/Firefox Dev Tools). I've had no luck on this front as no matter how I specify it, it appears to just break because the URL itself is inaccessible -- which it will be until our network requests go through.

**Comment by jainamanjain** [comment]
Currently, we do not support custom headers in the request made by function `getTokenUsingBasicAuth`. Thus, above scenario in which you are adding `headers` as a parameter to `getTokenUsingBasicAuth` function would not work

**Comment by Lovakumar** [comment]
Currently, we do not support custom headers in the request made by function getTokenUsingBasicAuth. Thus, above scenario in which you are adding headers as a parameter to getTokenUsingBasicAuth function would not work
