### ISSUE TITLE
Download build artifacts in Release deployment fails: ArtifactEngine.js unhandled rejection due to "read ECONNRESET"

### ISSUE THREAD

**Issue by Shakevg** [microsoft/azure-pipelines-extensions#638]
This error occurs when running the Azure Dev Ops release built-in Download Artifacts from a build pipeline, artifactEngine.js throws undhandled rejection due to "read ECONNRESET".

There is no information in the regular logs if there was a retry or not to handle this problem.

We have about 30 of release Agents and most of them succeed; but often the engine threw the exception.

Looks like similar to https://github.com/Microsoft/azure-pipelines-extensions/issues/597

I'm logging the issue here, since this project owns the artifactEngine.js file.

There is output of the task execution:

```
==============================================================================
Task         : Download build artifacts
Description  : Download files that were saved as artifacts of a completed build
Version      : 0.153.1
Author       : Microsoft Corporation
==============================================================================
_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.153.1\node_modules\artifact-engine\Engine\artifactEngine.js:157
##[error]artifact-engine: unhandled rejection Error: read ECONNRESET
     throw err;
     ^
 
Error: read ECONNRESET
     at exports._errnoException (util.js:1018:11)
     at TLSWrap.onread (net.js:568:26)
 ##[error]Unhandled: read ECONNRESET
 ##[error]Unhandled: read ECONNRESET
 ##[error]artifact-engine: unhandled exception Error: read ECONNRESET
 ##[error]Exit code 7 returned from process: file name 'externals\node\bin\node.exe', arguments '"_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.153.1\main.js"'.
```

**Comment by thiyagart1981** [comment]
We too facing the issue today morning

**Comment by kmkumaran** [comment]
@Shakevg @thiyagart1981 - The issues in this repo tracks only the tasks that are present in this repo. can you please open this specific issue in https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks repo, where the download build artifacts task is present for further follow-up.

**Comment by Shakevg** [comment]
Created new issue on tasks repo https://github.com/microsoft/azure-pipelines-tasks/issues/10702

**Comment by kmkumaran** [comment]
Thanks @Shakevg . Since we have the issue in proper repo, I will mark this issue as closed.
