### ISSUE TITLE
TeamCity Extension to include network documentation 

### ISSUE THREAD

**Issue by ryanvella** [microsoft/azure-pipelines-extensions#644]
This extension should include a network documentation, ie. Ports needed for DevOps to connect with TC Server.

**Comment by Lovakumar** [comment]
Adding @omeshp to provide required data.

**Comment by Lovakumar** [comment]
@omeshp should we add this TeamCity service connection?

**Comment by omeshp** [comment]
All the communication happens on http/https ports which are already required for agents to work.
