### ISSUE TITLE
Task 'IISWebAppDeploy' (1.4.6/1.4.7) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

### ISSUE THREAD

**Issue by jafin** [microsoft/azure-pipelines-extensions#652]
When using WinRM - IIS Web App Deployment task, v 1.4.6 we are receiving the following pipeline warning:

```
Task 'IISWebAppDeploy' (1.4.6) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
```

**EDIT:  Also appears on 1.4.7 (log below)**

```
WinRM - IIS Web App Deployment
2019-07-26T03:04:47.3917020Z Description  : Connect via WinRM, to deploy Web project locally on IIS, using Web Deploy
2019-07-26T03:04:47.3917550Z Version      : 1.4.7
2019-07-26T03:04:47.3917853Z Author       : Microsoft Corporation
2019-07-26T03:04:47.3917975Z Help         : [More Information](http://aka.ms/IISWebDeploy)
2019-07-26T03:04:47.3918119Z ==============================================================================
2019-07-26T03:04:47.4081210Z ##[warning]Task 'IISWebAppDeploy' (1.4.7) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
``

**Comment by kcnighsurf** [comment]
Getting the same issue
![image](https://user-images.githubusercontent.com/53189318/61649244-5a20f480-ac6e-11e9-8af9-676de84c4598.png)

**Comment by rajatagrawal-dev** [comment]
This warning has been recently added by the agent so that task authors start to use the new powershell handlers and stop relying on the legacy powershell handlers.

Since utilizing the new powershell handler might involve re-writing the task and creating a new major version, the resolution of this warning will take time. I can't give any ETA on this at the moment.

**Comment by 20shivangi** [comment]
@jafin Please use version 1.4.7 , no warning is coming in that version

**Comment by gerbenvl** [comment]
> Since utilizing the new powershell handler might involve re-writing the task and creating a new major version, the resolution of this warning will take time. I can't give any ETA on this at the moment.

Any updates on this one? Will it be picked up?

**Comment by RoopeshNair** [comment]
@gerbenvl  - we haven't been able to get to this, as the team is focussed on issues that impact broader set of customers. We know this is important for you, we will continue to monitor this.

**Comment by MidTNProjects** [comment]
We are also now getting
##[warning]Task 'Security static source code analysis' (88.0.11) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

So it sounds like there is nothing we can do for this currently?

**Comment by chshrikh** [comment]
@MidTNProjects for which task it is coming for you ?

**Comment by gertvdh** [comment]
same for SqlDacpacDeploy

2019-11-26T11:05:37.2552681Z ##[warning]Task 'SqlDacpacDeploy' (1.3.12) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

**Comment by 20shivangi** [comment]
@jafin We have moved the tasks SqlDacpacDeloy, IISWebAppDeploy and IISWebAppMgmt to PS3 handler. Please use the latest version of these tasks, now the warning will not come.

**Comment by neetu-khatra** [comment]
##[warning]Task 'Update AssemblyInfo' (1.2.0) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
![image](https://user-images.githubusercontent.com/16982524/92694669-063b0880-f365-11ea-93e4-d8665dcd0c33.png)

Can't see any other version for update assembly info task. Please help with this.

**Comment by neetu-khatra** [comment]
##[warning]Task 'Update AssemblyInfo' (1.2.0) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
image

Can't see any other version for update assembly info task. Please help with this.

@kmkumaran kmkumaran assigned chshrikh and nadesu and unassigned RoopeshNair, kmkumaran and rajatagrawal-dev on 11 Sep 2020

----------
Any Updates on this will be really helpful? @kmkumaran @chshrikh @nadesu

**Comment by chshrikh** [comment]
we haven't been able to get to this, as the team is focused on issues that impact broader set of customers. We know this is important for you, we will continue to monitor this.
