### ISSUE TITLE
[Terraform task] Unable to use parameters for AzureRM Backend configuration

### ISSUE THREAD

**Issue by shep1987** [microsoft/azure-pipelines-extensions#655]
We use task groups to be able to configure multiple pipelines with similar settings.

We can set the subscription with a parameter but the other fields must be selected from the dropdown. Would it be possible to relax this restriction so all fields can be set by parameters?

**Comment by ksix** [comment]
@shep1987 we do exactly the same thing... they probably just looked at it as field validation without considering all the ways people use it today.

**Comment by RoopeshNair** [comment]
Feedback taken. We will review this. Thanks

**Comment by johnburns320** [comment]
I'm able to specify environment variables for the backend inputs now.

**Comment by RoopeshNair** [comment]
Thanks for confirming. Closing the issue
