### ISSUE TITLE
[Terraform task] Error: Cannot find module 'azure-pipelines-task-lib/task'

### ISSUE THREAD

**Issue by johnburns320** [microsoft/azure-pipelines-extensions#657]
Pool: Hosted Ubuntu 1604
```
##[section]Starting: Install Terraform 0.11.14
==============================================================================
Task         : Terraform tool installer
Description  : Find in cache or download a specific version of Terraform and prepend it to the PATH
Version      : 0.0.15
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/AA5jd97)
==============================================================================
module.js:471
    throw err;
    ^

Error: Cannot find module 'azure-pipelines-task-lib/task'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vsts/work/_tasks/TerraformInstaller_a4789e5d-f6e8-431f-add9-379d640a883c/0.0.15/src/index.js:11:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
##[error]Exit code 1 returned from process: file name '/home/vsts/agents/2.154.3/externals/node/bin/node', arguments '"/home/vsts/work/_tasks/TerraformInstaller_a4789e5d-f6e8-431f-add9-379d640a883c/0.0.15/src/index.js"'.
##[section]Finishing: Install Terraform 0.11.14
```

**Comment by brennaman** [comment]
I've got the same issue.

**Comment by bryceafoster** [comment]
I have the same issue.

**Comment by mrptsai** [comment]
I have the same issue

**Comment by ssarwa** [comment]
I am running into the same issue.

**Comment by hawk3yez** [comment]
Same issue and I've tried on both Hosted/Private agent pools.

**Comment by ausfestivus** [comment]
This issue has now appeared on the Developer Forums https://developercommunity.visualstudio.com/content/problem/670951/terraform-tool-installer-not-working.html.

Adding cross references.

**Comment by RoshanKumarMicrosoft** [comment]
We had already identified the issue .. We are fixing it.

**Comment by ausfestivus** [comment]
> We had already identified the issue .. We are fixing it.

Thanks for the update @RoshanKumarMicrosoft

**Comment by ausfestivus** [comment]
Morning @RoshanKumarMicrosoft 

Can we get an indicative timeline on this? Ive got pipelines to create that need to use the task and I'm unable to do so because of this issue.

**Comment by ausfestivus** [comment]
For everyone here, I just ran a pipeline and the Terraform Install task succeeded.
Perhaps it's already fixed?

**Comment by johnburns320** [comment]
I re-deployed and got a successful result. Is there a commit that can be associated with this fix?

**Comment by johnburns320** [comment]
I'm good with this being closed. I'd prefer the maintainers to do so referencing an appropriate commit.

**Comment by RoshanKumarMicrosoft** [comment]
Fixed in this [Commit ](https://github.com/microsoft/azure-pipelines-extensions/pull/658) and released new extension version.  Closing this issue.
