### ISSUE TITLE
Terraform extension: State not stored to Azure storage account

### ISSUE THREAD

**Issue by janegilring** [microsoft/azure-pipelines-extensions#664]
Extension: https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks&targetId=c604e216-44c6-46a3-b271-7de25916a69e&utm_source=vstsproduct&utm_medium=ExtHubManageList

Installed version: 0.1.3 (Latest)

Backend configuration is configured like this in the pipeline:
![2019-08-08_11-10-13](https://user-images.githubusercontent.com/2039662/62692086-4b597200-b9d0-11e9-8002-2e91d06eeb5b.png)

terraform init runs fine:
![2019-08-07_15-47-54](https://user-images.githubusercontent.com/2039662/62691997-1f3df100-b9d0-11e9-92cc-5ae75fc1fdb3.png)

However, no state file is found in the storage account:
![2019-08-08_11-34-13](https://user-images.githubusercontent.com/2039662/62692190-7e036a80-b9d0-11e9-9c10-2ef1d917fd54.png)

Hence, a full deployment is being triggered every time the deployment runs.

**Comment by davidgurnsey** [comment]
I'm experiencing the same thing.

**Comment by davidgurnsey** [comment]
I found my issue. I had neglected to add the `terraform` stanza to my main.tf
Without this, the `init` command doesn't configure the remote backend.
[Backends: Configuration](https://www.terraform.io/docs/backends/config.html)
Hope that helps.

**Comment by janegilring** [comment]
Interesting - I thought that specifying a remote backend in a .tf file was not requried when terraform is called with the following parameters by the extension:

C:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe init -backend-config=storage_account_name=jerterraformstate -backend-config=container_name=tfstate -backend-config=key=azure/terraform-demo-rg.tfstate -backend-config=resource_group_name=jer-management-rg -backend-config=arm_subscription_id=xxxxxx-e9b5-4648-ab8b-815e2ef18a2b -backend-config=arm_tenant_id=*** -backend-config=arm_client_id=*** -backend-config=arm_client_secret=***

**Comment by davidgurnsey** [comment]
Yeah, I'd have thought so too. But adding
`
terraform {
  backend "azure" {}
}
`
to my main did the trick.

**Comment by janegilring** [comment]
I tried the same, but got the following error:

![2019-08-09_13-36-08](https://user-images.githubusercontent.com/2039662/62776359-ac557880-baaa-11e9-91fa-664b113ff06e.png)

![2019-08-09_13-35-10](https://user-images.githubusercontent.com/2039662/62776326-8e881380-baaa-11e9-923e-9ab40680897b.png)

Anyway, is the requirement to add the backend block documented somewhere?

**Comment by davidgurnsey** [comment]
Wow, that's weird. I just tried it that way too and got the same error.

It was github markdown that collapsed my stanza to a single line. 
![AzureTerraformJAN](https://user-images.githubusercontent.com/12236747/62776714-62a06a00-ba79-11e9-8543-b44bb3b44c6c.PNG)

That change broke it.
So, maybe just try expanding the staza.

**Comment by janegilring** [comment]
That did the trick here as well - thanks.

Let's just wait and see whether this is a requirement, if so - this issue can be closed.

**Comment by StefanSchoof** [comment]
Yeah, but this makes the reuse of terraform files for local testing harder.
I want to run my terraform localy and test with my own subscription. The Pipeline should apply those changes to different Stages and store in a azure Backend. For a everyone you use the terraform to have a azure backend makes it harder.

**Comment by StefanSchoof** [comment]
My current workaround is having a step to create a tf file with the content:
```yml
  - powershell: New-Item -Name "backend.tf" -Value "terraform {`r`nbackend `"azure`" {}`r`n}"
```

**Comment by RoshanKumarMicrosoft** [comment]
When using partial configuration, Terraform requires at a minimum that an empty backend configuration is specified in one of the root Terraform configuration files, to specify the backend type. For example:

terraform {
  backend "consul" {}
}

Terraform official documentaion [Link](https://www.terraform.io/docs/backends/config.html#partial-configuration)

**Comment by janegilring** [comment]
Thanks @RoshanKumarMicrosoft - I'll close the issue. Although, it would be nice if this requirement is mentioned in the documentation for the Azure DevOps Terraform extension.

@StefanSchoof Nice - thanks for sharing.

**Comment by danielalvesleandro** [comment]
Hi,

I'm experiencing this same issue, using Terraform 0.15.3. I've already tried to expand it to:

`terraform {  backend "azurerm" {}}`

But then Terraform crashes as below:

[terraform_panic.txt](https://github.com/microsoft/azure-pipelines-extensions/files/6455544/terraform_panic.txt)

I've also tried to do the mentioned workaround creating the file using a shell command but it didn't work. Is any other way to solve that?

Thanks.

**Comment by techadmin1982** [comment]
Is there any update on this ?. In my case I am using Terraform extension from MicrosoftDevLabs. The configuration runs flawless but no state file gets created in Azure Storage Account container. I first tried to run main.tf without the backend codeblock thinking extension task will handle that (because i mentioned the backend conif in extension task) - no go. Then i removed the backend codeblock from main.tf and run it again - no go.

**Comment by 5anjay5engupta** [comment]
> terraform { backend "azure" {} }

Worked for me too, thanks a lot.

**Comment by williamrobinsonlightstream** [comment]
terraform { backend "azurerm" {} }
not just "azure"
