### ISSUE TITLE
[terraform] Why warn for multiple provider?

### ISSUE THREAD

**Issue by StefanSchoof** [microsoft/azure-pipelines-extensions#667]
The terraform task checks for multiple provider 
https://github.com/microsoft/azure-pipelines-extensions/blob/7c5860fb5e393c59db8d02eac8bf26280c71d86c/Extensions/Terraform/Src/Tasks/TerraformTaskV1/src/base-terraform-command-handler.ts#L42

I have a terraform with azurerm and the random provider and see this warning. The warning contains no information what is the problem with multiple providers. I think the warning should contain some background information why this might be a problem or should only shown if you are using multiple cloud provider (and not things like random, null, etc)

**Comment by RoshanKumarMicrosoft** [comment]
This is by design we are supporting one provider per task (Just to avoid multiple backend configuration and which one to store state file). If you want to use multiple provider Please split your configuration file and add each task per provider.

**Comment by StefanSchoof** [comment]
@RoshanKumarMicrosoft Thanks for the reply.

I have 
```terraform
resource "random_string" "sql_administrator_password" {
  length = 20
}

resource "random_string" "sql_administrator" {
  length = 20
}

resource "azurerm_sql_server" "this" {
  name                         = "sqlservername${var.stagename}"
  resource_group_name          = var.resource_group_name
  location                     = data.azurerm_resource_group.this.location
  version                      = "12.0"
  administrator_login          = random_string.sql_administrator.result
  administrator_login_password = random_string.sql_administrator_password.result
}
```

This uses random and azurerm provider. I think this is impossible to split. You should only warn if there are multiple backend provider (like azure, gcp, aws) and not things like random or null. Also should the warning message contain some background information, what the problem is.

**Comment by RoshanKumarMicrosoft** [comment]
We are just supporting three provider azure, gcp, aws but for other we will add in future which is already in backlog .
