### ISSUE TITLE
[terraform install] option to download "latest"

### ISSUE THREAD

**Issue by SebRosander** [microsoft/azure-pipelines-extensions#669]
Would be awesome if it's possible to choose "latest" version of Terraform to be installed. Since the phase of new releases are kinda high, it would be great to have an option always installing the latest version of Terraform so you don't have to update it manually every time there is a new version available by Hashicorp. 

Just like in https://marketplace.visualstudio.com/items?itemName=petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform&targetId=726d6728-bb54-40a8-9f79-68d17430f31f

e.g.

`
function Install-Terraform
{
    $version = Get-VstsInput -Name Version

    # Need to force using more up-to-date encryption protocols; Hashicorp is on-point deprecating broken ones.
    [System.Net.ServicePointManager]::SecurityProtocol = `
                [System.Net.SecurityProtocolType]::Tls11 -bor 
                [System.Net.SecurityProtocolType]::Tls12 -bor `
                [System.Net.SecurityProtocolType]::Tls -bor `
                [System.Net.SecurityProtocolType]::Ssl3

    $terraformbaseurl = "https://releases.hashicorp.com/terraform/"
    $path = "c:\terraform-download"

    $regex = """/terraform/([0-9]+\.[0-9]+\.[0-9]+)/"""

    $webpage = (Invoke-WebRequest $terraformbaseurl -UseBasicParsing).Content

    $versions = $webpage -split "`n" | Select-String -pattern $regex -AllMatches | % { $_.Matches | % { $_.Groups[1].Value } }
    if ($version -eq "latest")
    {
        $version = $versions[0]
    }
    else
    {
        if (-not $versions.Contains($version))
        {   
            throw [System.Exception] "$version not found."
        }
    }

    $tempfile = [System.IO.Path]::GetTempFileName()
    $source = "https://releases.hashicorp.com/terraform/"+$version+"/terraform_"+$version+"_windows_amd64.zip"
`

**Comment by RoshanKumarMicrosoft** [comment]
We had already Terraform tool installer task which comes through [Terraform extension ](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks). 
![image](https://user-images.githubusercontent.com/33001640/63243438-21c60380-c278-11e9-9351-59d61715bdd2.png)
You can install any version of Terraform using this task

**Comment by SebRosander** [comment]
Yes, but not simply use ”latest”. You need to specify the version. I allways want to use the latest. Now I need to update in my .yml when there is a new update out for Terraform.

**Comment by RoshanKumarMicrosoft** [comment]
Current time we are not supporting this. This [repo](https://github.com/microsoft/azure-pipelines-extensions/tree/master/Extensions/Terraform/Src) is also available for contribution. You can also raise PR and assign to me. We will be happy to take changes.
