### ISSUE TITLE
Terraform: Local Backend Option

### ISSUE THREAD

**Issue by AdamCoulterOz** [microsoft/azure-pipelines-extensions#688]
Can we have an option to specify different backend options?

1. **Local** - which is needed in order to run build validation on terraform scripts which aren't actually applied anywhere.

2. **Terraform Cloud** - which now supports a free backend. Would also need a service connection for this.

**Comment by AdamCoulterOz** [comment]
Thinking about this more broadly - I've noticed the `Provider` attribute in the Microsoft Terraform Task only affects the `Backend` configuration section visibility. When the `init` option is selected, the `Provider` attribute should be hidden, and the other option for `Backend` be exposed. So that is the fix here. Pretty simple... I'll submit a PR if I get time later today.

![Task Configuration](https://user-images.githubusercontent.com/6822248/64755195-acdfa400-d56d-11e9-9add-e4040f0fb291.png)

**Comment by RoshanKumarMicrosoft** [comment]
@AdamCoulterOz We are open for contribution .You can submit PR and assign to me.
But I have few query :- 
1. Do you want backend must be one more option like Local ? Current time we are not supporting local but may be in future we can also support it.
2.  When the init option is selected, the Provider attribute should be hidden, and the other option for Backend be exposed. I didn't get this point. Are you planning to show all service connection if user will select init command ?

**Comment by AdamCoulterOz** [comment]
@RoshanKumarMicrosoft The "Provider" attribute needs to be split in 2, one for the service connection to the actual `Provider` for provisioning and another for the `Backend` provider. These are logically different things and will often be different.

**Comment by RoshanKumarMicrosoft** [comment]
@AdamCoulterOz  We have a different design we are not supporting multiple operation in single task. We require service connection and backend configuration during init operation of terraform for provisioning and for apply operation we only needed service connection.
We need service connection for authentication and provider attribute we needed to manage state file.
