### ISSUE TITLE
TeamCity extension: Setting scheduled release trigger fails with Azure DevOps Server 2019.1

### ISSUE THREAD

**Issue by pascalberger** [microsoft/azure-pipelines-extensions#690]
With latest version of TeamCity extension running on Azure DevOps Server 2019.1 I get the following error while trying to save a release definition which contains a TeamCity build artifact and has a schedule set:

```
Cannot have default version as 'Specify at the time of release creation' for the artifact 'Build' since a scheduled trigger is set on the release pipeline
```

Error is caused by setting a schedule. Without a schedule the definition can be saved. This worked fine with previous version of Azure DevOps Server.

**Comment by pascalberger** [comment]
I saw that the selection for default version was implemented for the TeamCity artifact back in December with https://github.com/microsoft/azure-pipelines-extensions/commit/bd9d7826b8190520648d031db081759911fee2c7#diff-b5b5a4f894965f60ae124cf0e9eb7987, but no version was released since then.

@omeshp Would it be possible to release a new version of the TeamCity extension to see if this fixes the issue?

**Comment by omeshp** [comment]
@pascalberger Sure, I will get it updated.

**Comment by omeshp** [comment]
Hi @pascalberger, we have updated the extension. can you try out the changes and let us know?

**Comment by pascalberger** [comment]
@omeshp Thanks for the quick update 👍 

I tested with the new version and after setting the default version to `Latest` it's now possible again to define a scheduled triggering.
