### ISSUE TITLE
Terraform: It is impossible to create AKS via terraform using Azure DevOps service principal

### ISSUE THREAD

**Issue by WindMaster** [microsoft/azure-pipelines-extensions#698]
**Extension: Terraform**

We have service principal credentials in Azure DevOps services. In terraform main file there is a section with "azurerm_kubernetes_cluster" resource. The mandatory fields are:
  service_principal {
    client_id     = "${var.client_id}"
    client_secret = "${var.client_secret}"
  }

By security reason there is no possibility to take the client secret from azurerm provider. We can run only terraform scripts via Terraform extension in Azure DevOps services. So, is there any way to create a cluster in our case?

Thank you!

**Comment by RoshanKumarMicrosoft** [comment]
@WindMaster "Can run only terraform scripts via Terraform extension in Azure DevOps services" No you can't We require service endpoint for backend configuration. Current time we are not supporting local backend configuration. 
If you still face any issue or blocked please ping ur skypeId on RM_Customer_Queries@microsoft.com. So we have a quick call.
