### ISSUE TITLE
[Terraform] Issue with multiple iterations of the same module (creating security Groups)

### ISSUE THREAD

**Issue by steven-dougal** [microsoft/azure-pipelines-extensions#700]
Extension: Terraform

We're trying to get ADO to deploy our terraform configurations.

With the terraform AWS module for security groups we call it several times in the same folder (config file for each group).

Init and plan work without issue but when it comes to the apply we're getting the attached error:

![tf_sg_error](https://user-images.githubusercontent.com/15940731/65777483-046c3b00-e13c-11e9-87ce-bb8e282aa78f.PNG)

Additional info we did have this with another config folder but got around it by using a shared credential file in the config, but that hasn't helped in this case.

Cheers,
Steven

**Comment by steven-dougal** [comment]
I've solved the issue..

I had to pass the location of the shared credentials file to the data modules that were collection info from other state files.

**Comment by RoshanKumarMicrosoft** [comment]
@steven-dougal I am closing this issue. If you still face any issue please ping us on RM_Customer_Queries@microsoft.com.
