### ISSUE TITLE
Terraform Enterprise Support

### ISSUE THREAD

**Issue by StephenRSkinner** [microsoft/azure-pipelines-extensions#703]
There should be a way to configure the Terraform extension to use TE instead of only connecting directly to the target environment (AWS for my case). Currently a file must be manually created under the agent account roaming profile to redirect and ignore the TFS connection configuration.

**Comment by RoshanKumarMicrosoft** [comment]
@StephenRSkinner  Can you please ping your skypeId on RM_Customer_Queries@microsoft.com So we can have a quick call to understand it better.

**Comment by StephenRSkinner** [comment]
I'm not sure what you're asking for, but maybe I can explain better.

Currently, you can configure the Terraform AWS service connection in TFS 2018 on-premise. I'm asking for support to configure a Terraform Enterprise service connection as well, so we can pick that as an option. Currently, to execute tasks on Terraform Enterprise, a file has to be put into C:\Users\{ServiceAccount}\AppData\Roaming folder on every server running the TFS agent where terraform scripts will be executed. This is not a practical approach. The task needs to support calling Terraform Enterprise instead as an option.

**Comment by Roshan-Kumar-Microsoft** [comment]
Not supported now .We are also encouraging for contribution ..Even you can raise PR and assign to me
