### ISSUE TITLE
IIS Virtual Directory Update not using credentials in file AppCmdOnTargetMachines.ps1

### ISSUE THREAD

**Issue by Keith-B** [microsoft/azure-pipelines-extensions#704]
The file _AppCmdOnTargetMachines.ps1_ contains a function called **Update-VirtualDirectory**. This then calls **Test-Path** without using the authentication credentials passed into the Update-VirtualDirectory function. This causes deployment pipelines in Azure DevOps to fail with 'Access is Denied' when  virtual directories have different logon credentials. The credentials should be passed through to the **Test-Path** cmdlet.

**Comment by 20shivangi** [comment]
@Keith-B Can you please share debug logs of the pipeline by setting system.debug to true

**Comment by 20shivangi** [comment]
@Keith-B Any update ?

**Comment by 20shivangi** [comment]
Feel free to open the issue if face any. Closing this as there is no response.

**Comment by BlackyTheDruide** [comment]
Hi, 

I have the same Problem. The error seems to be on the mentioned file.

https://github.com/microsoft/azure-pipelines-extensions/blob/76d1a318faaa6191d84240f3f28a4954604e0f5b/TaskModules/powershell/TaskModuleIISManageUtility/AppCmdOnTargetMachines.ps1#L618

The Method Test-Path is used without the $physicalPathAuthenticationCredentials.

https://github.com/microsoft/azure-pipelines-extensions/blob/76d1a318faaa6191d84240f3f28a4954604e0f5b/TaskModules/powershell/TaskModuleIISManageUtility/AppCmdOnTargetMachines.ps1#L609

When you configure a virtual Directory with specific credential the Test-Path will fail with an Access Denied.
