### ISSUE TITLE
Terraform: Allow state files to be stored in a different subscription

### ISSUE THREAD

**Issue by whyneus** [microsoft/azure-pipelines-extensions#707]
When running an init, we can define details on where to house the state file if using an Azure backend (eg. resource group, storage account, container name, state file name). DevOps accesses this storage account using a service connection tied to the subscription.

If we want to then plan/apply into a different subscription, DevOps can't access the storage account where the state file is.

```Error: ‌Error loading state: Error retrieving keys for Storage Account &quot;blahtestexample&quot;: storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest&#x2F;azure: Service returned an error. Status=404 Code=&quot;ResourceGroupNotFound&quot; Message=&quot;Resource group &#x27;example-rsg&#x27; could not be found.&quot;‌```

It would be good to allow the the state file to be sourced from a different subscription relative to the subscription being deployed into rather than using a workaround like specifically defining the target sub as an additional command argument.

**Comment by Roshan-Kumar-Microsoft** [comment]
This is not supported for now....We are also encouraging for contribution ..Even you can raise PR and assign to me.

**Comment by NK74** [comment]
Hello,

Is it solved ??

I had the same issue in my TF Stack, i'm trying to store my TFStates in a central subscription (inside a dedicated storage account) and deploy in a different subscription
`Error: Error loading state: Error retrieving keys for Storage Account "mycentralstorage": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'my-central-tfstates-rg' could not be found."`

In the Terraform Extension parameters: https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/Terraform/Src/Tasks/TerraformTaskV1/Strings/resources.resjson/en-US/resources.resjson

The Terraform extension should now allow 2 options
- "loc.input.help.environmentServiceNameAzureRM": "Select an Azure Resource Manager subscription for the deployment"
- "loc.input.help.backendServiceArm": "Azure resource manager subscription for the terraform backend configuration"

Up please :)

**Comment by halbeezy** [comment]
is there an update on this?

**Comment by nadesu** [comment]
Updated the assignment. 
@vijayma - pls triage the request & involve the right engg team. Thanks!
