### ISSUE TITLE
System.InvalidOperationException: The environment block used to start a process cannot be longer than 65535 bytes.  Your environment block is 69981 bytes long.  Remove some environment variables and try again.

### ISSUE THREAD

**Issue by amccool** [microsoft/azure-pipelines-extensions#709]
see
https://github.com/microsoft/azure-pipelines-tasks/issues/11631

https://github.com/microsoft/azure-pipelines-extensions/blob/master/TaskModules/powershell/TaskModuleSqlUtility/TaskModuleSqlUtility.psm1#L28

**Comment by amccool** [comment]
@kmkumaran @chshrikh could I get an ETA for a review?   Currently I have a painful workaround, but I need to get a release out to testing asap.

**Comment by amccool** [comment]
I now have 3 failing task in my release pipeline.   This is becoming a major blocker.   Should I open an issue in a different place?

**Comment by amccool** [comment]
bump

**Comment by eaarora-ms** [comment]
@amccool  Can you please share debug logs of the pipeline by setting system.debug to true?

**Comment by eaarora-ms** [comment]
> @amccool Can you please share debug logs of the pipeline by setting system.debug to true?

Saw your other issue. I will get back to you with an update.

**Comment by amccool** [comment]
@eaarora-ms can I PM you the logs? Not sure if there is any confidential things in them.

**Comment by amccool** [comment]
this a log from a related issue, a different task, but the same issue
[tasklog_75.log](https://github.com/microsoft/azure-pipelines-extensions/files/3880677/tasklog_75.log)

**Comment by eaarora-ms** [comment]
Following on task repo. Link: https://github.com/microsoft/azure-pipelines-tasks/issues/11631
