### ISSUE TITLE
Feature: Ability to use local backend instead of forcing remote backend

### ISSUE THREAD

**Issue by mattjlubbers** [microsoft/azure-pipelines-extensions#717]
When using the Terraform plugin, there are a few use cases where you may not want to use a remote backend. A good example of this is a build pipeline. If I would like to store the .tfstate file as an artifact, we are forced to implement a remote backend per cloud provider. We love the ability to use Azure, GCP, and AWS but I feel enforced to use each providers backend when a pipeline doesn't care about the backend but more of the execution of the Terraform file.

Hope this helps!

**Comment by Roshan-Kumar-Microsoft** [comment]
Not supported now but it is already in pipeline ...We are also encouraging to contribution ..Even you can raise PR and assign to me
