### ISSUE TITLE
Support workspace in the terraform extension

### ISSUE THREAD

**Issue by guojian83** [microsoft/azure-pipelines-extensions#722]
Currently the workspace subcommand is not supported.
Ideally, the workspace can be used to deploy to different environment (stage) in a release.
i.e. terraform workspace new dev

I was able to work around just by using command line:
terraform workspace select dev || terraform workspace new dev

However, when accessing terraform.workspace in the tf, it showed 'default' instead of 'dev' even the workspace was set to 'dev' in the standard command line.
Any idea why this is happening?

**Comment by Roshan-Kumar-Microsoft** [comment]
@guojian83 Can you please share debug log to  RM_Customer_Queries@microsoft.com.

**Comment by guojian83** [comment]
Update:
Just realised the commands to set up the workspace wasn't using the terraform folder as its working directory. As soon as that's updated, its all working now.
I only found this configuration problem when sending you the debug log.
Thanks for the support!
