### ISSUE TITLE
Terraform: bug in TerraformTaskV1 plan task with command options

### ISSUE THREAD

**Issue by ahukin** [microsoft/azure-pipelines-extensions#729]
**Bug**: the terraform plugin TerraformTaskV1 plan task doesn't execute correctly when command options are supplied such as -var or -var-file.

The `terraform plan` command is run twice in this task: once without `-out` and then with `-out`.
The first plan runs correctly but the second is not passed the command options.  The quick fix is to pass the command options to the second plan. e.g.

file: `azure-pipelines-extensions/Extensions/Terraform/Src/Tasks/TerraformTaskV1/src/base-terraform-command-handler.ts` 

```
abstract class BaseTerraformCommandHandler {
...
method: public setOutputVariableToPlanFilePath() {
...
```
**Existing code:**
```
144             let planCommand = new TerraformAuthorizationCommandInitializer( 
145                 "plan", 
146                 tasks.getInput("workingDirectory"), 
147                 tasks.getInput(serviceName, true), 
148                 `-out=${binaryPlanFilePath}` 
149             ); 
```

**Replacement code:**
```
144             let planCommand = new TerraformAuthorizationCommandInitializer( 
145                 "plan", 
146                 tasks.getInput("workingDirectory"), 
147                 tasks.getInput(serviceName, true), 
...                 tasks.getInput("commandOptions"),
148                 `-out=${binaryPlanFilePath}` 
149             ); 
```

I'd fix it but I'm not really a javascript / typescript guy.

Many thanks

**Comment by Roshan-Kumar-Microsoft** [comment]
@ahukin Can you please share debug log to RM_Customer_Queries@microsoft.com

**Comment by smushtaq** [comment]
Facing the same problem. why is it running plan twice. it should be running it only once. Is there any fix on the roadmap?

**Comment by liamfoneill** [comment]
@smushtaq I can't help you with this issue as I am experiencing it myself but if you use '-no-color' in "Additonal Command Arguements" it makes Terraform plan output cleaner as there is some problem in Azure DevOps displaying the colored plus and minus symbols.

**Comment by smushtaq** [comment]
> @smushtaq I can't help you with this issue as I am experiencing it myself but if you use '-no-color' in "Additonal Command Arguements" it makes Terraform plan output cleaner as there is some problem in Azure DevOps displaying the colored plus and minus symbols.

Thanks @liamfoneill for the update. Do you know who can work on this to get it resolved. Should be a quick fix for the team.

**Comment by omelhus** [comment]
I've got this exact same issue and I've submitted a pull request (#741) that should solve it.

**Comment by Roshan-Kumar-Microsoft** [comment]
Merged PR ..Will release updated version by this week .
