### ISSUE TITLE
IISWebAppManagementOnMachineGroup, Add-Type failed when environment block is large

### ISSUE THREAD

**Issue by amccool** [microsoft/azure-pipelines-extensions#730]
if a large number of build artifacts are in a release definition, the environment block grows large

tasks that use Add-Type will fail

see #709 

and #711 for the PR

Add-Type : The environment block used to start a process cannot be longer than 65535 bytes.  Your environment block is 73567 bytes long.  Remove some environment variables and try again.
At C:\azagent\A1\_work\_tasks\IISWebAppManagementOnMachineGroup_1b2aec60-dc49-11e6-9b76-63056e018cac\0.5.13\ps_modules\TaskModuleIISManageUtility\TaskModuleIISManageUtility.psm1:26 char:1
+ Add-Type -WarningAction SilentlyContinue -Debug:$false -TypeDefinitio ...

[tasklog_75.log](https://github.com/microsoft/azure-pipelines-extensions/files/3880672/tasklog_75.log)

**Comment by eaarora-ms** [comment]
@amccool  Sorry for the delay in response but we are already looking at your previous issues and PRs. You can track the status at:
https://github.com/microsoft/azure-pipelines-tasks/issues/11631
I am closing this.
