### ISSUE TITLE
IIS App Pool - Support Empty Passwords/Managed Service Accounts

### ISSUE THREAD

**Issue by MichaelClaffey** [microsoft/azure-pipelines-extensions#735]
In the "WinRM - IIS Web App Management" step you must pass a value for the IIS Application Pool Password when creating or updating an Application Pool.

This looks to be the case as the [Get-PSCredentials](https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppMgmt/IISWebAppMgmtV2/AppCmdOnTargetMachines.ps1#L836) function runs a `IsNullOrWhiteSpace()` test on both the user name and password:
```PowerShell
function Get-PSCredentials {

    param (
        [string][AllowNull()] $username, 
        [string][AllowNull()] $password 
    )

    if ([string]::IsNullOrWhiteSpace($username) -or [string]::IsNullOrWhiteSpace($password)) {
        return $null
    }
```

 [Group Managed Service Accounts](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/getting-started-with-group-managed-service-accounts) do not need a password set.

If you run a release with an empty Application Pool Password the pool will be created, but the user name will be empty and the site will not start.

**Comment by Roshan-Kumar-Microsoft** [comment]
@MichaelClaffey This is not supported for now but due to some other priority work we are not able to pick this for now .
