### ISSUE TITLE
Terraform: add support for the `refresh` command

### ISSUE THREAD

**Issue by ausfestivus** [microsoft/azure-pipelines-extensions#742]
Afternoon,

Can we please have support for the refresh command option added?

I am using Azure DevOps YAML pipelines to do the build, deploy and destroy of non-prod environments. I have a very long running destroy task that more often than not fails due to a timeout.

Till the AzureRM provider 2.0 is released and broader support for timeouts is available (which may or may not actually fix the underlying issue here), I am having to re-run the destroy stage of the pipeline. I would like to run a refresh prior to the delete in case a previous delete stage run has failed and left the shared state in an inconsistent state.

**Comment by Roshan-Kumar-Microsoft** [comment]
@ausfestivus This is enhancement but due to other priority work we are not able to pick this for now. But we are open for contribution. You and raise PR and assign to us.

**Comment by ausfestivus** [comment]
Acknowledged @Roshan-Kumar-Microsoft 
Not sure I agree with the ticket closure as the actual suggestion isn't complete.
