### ISSUE TITLE
Terraform: Use backend configuration from tf-file

### ISSUE THREAD

**Issue by LukasVice** [microsoft/azure-pipelines-extensions#746]
Hi,
is it possible to use the configuration from the tf-file's terraform.backend section?
Currently I have to set it in the pipeline too - so I have to configure it twice.
Or do I miss some best practice?
Thanks.

**Comment by sephross** [comment]
Similar problem here. I would like to use remote state variables and subsequently multiple backends/state files configured across different modules in my build artifact.

This tool doesn't seem to let me do that as it mandates I have to configure the backend with the terraform init command and then overrides the local config.

**Comment by Roshan-Kumar-Microsoft** [comment]
@LukasVice Right now it is not supported to set terraform.backend section from tf-file's . It will be enhancement but due to other priority work we are not picking it now
