### ISSUE TITLE
Terraform plan provider warning with single provider

### ISSUE THREAD

**Issue by algattik** [microsoft/azure-pipelines-extensions#748]
Terraform plan shows the warning
```
##[warning]Multiple provider blocks specified in the .tf files in the current working drectory.
```

I only have one provider block defined. The code is at https://github.com/algattik/terraform-azure-pipelines-starter/tree/github.com/microsoft/azure-pipelines-extensions/issues/747

```
$ terraform providers
.
├── provider.azurerm =1.38.0
└── module.sqlserver
    └── provider.azurerm (inherited)
```

**Comment by smushtaq** [comment]
Also getting the same warning. Not sure why this is an issue.

Below are the logs

2019-12-23T11:34:35.6260751Z ##[section]Starting: Terraform apply
2019-12-23T11:34:35.6265766Z ==============================================================================
2019-12-23T11:34:35.6265860Z Task         : Terraform
2019-12-23T11:34:35.6265988Z Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
2019-12-23T11:34:35.6266076Z Version      : 0.0.142
2019-12-23T11:34:35.6266185Z Author       : Microsoft Corporation
2019-12-23T11:34:35.6266257Z Help         : [Learn more about this task](https://aka.ms/AA5j5pf)
2019-12-23T11:34:35.6266383Z ==============================================================================
2019-12-23T11:34:35.7729554Z [command]/opt/hostedtoolcache/terraform/0.12.17/x64/terraform providers
2019-12-23T11:34:36.1545312Z .
2019-12-23T11:34:36.1547094Z ├── provider.azurerm =1.34.0
2019-12-23T11:34:36.1547653Z └── provider.random
2019-12-23T11:34:36.1547805Z 
2019-12-23T11:34:36.1582949Z ##[warning]Multiple provider blocks specified in the .tf files in the current working drectory.
2019-12-23T11:34:36.1587107Z [command]/opt/hostedtoolcache/terraform/0.12.17/x64/terraform validate
2019-12-23T11:34:37.4669201Z [32m[1mSuccess![0m The configuration is valid.

**Comment by Roshan-Kumar-Microsoft** [comment]
@algattik We are not supporting Multiple provider blocks specified in the .tf files. It will be enhancement .Due to some other priority work we are not picking it now but we are open for contribution.

**Comment by pfilbin90** [comment]
> @algattik We are not supporting Multiple provider blocks specified in the .tf files. It will be enhancement .Due to some other priority work we are not picking it now but we are open for contribution.

@RoshanKumarMicrosoft - I am using an S3 backend which requires a terraform provider and an AWS provider.  My releases are failing because I have 2 providers instead of just the one AWS provder.

Does your statement above mean the this extension is incompatible with using S3 backend?  This would make the extension completely useless.

**Comment by algattik** [comment]
> @algattik We are not supporting Multiple provider blocks specified in the .tf files. It will be enhancement .Due to some other priority work we are not picking it now but we are open for contribution.

As the linked sample code shows, the issue trigger even when a single provider block is defined, as long as the provider is used in more than one module

**Comment by ztbrumbaugh** [comment]
I'd like this to be reopened. Using a single provider with multiple modules should not throw a warning like this. If modules are heavily utilized, it creates a lot of noise in the output window and in Azure Devops pipelines.

**Comment by thejanek** [comment]
So everything is deployed correctly but design of Terraform modules usage don't expect to use more then one a provider block - even if it will be inheritance...
Please Hashicorp - fix that.

**Comment by chrisjaimon2012** [comment]
Please fix this issue with multiple providers. We are blocked. Does anyone have any workaround to this?

**Comment by thejanek** [comment]
> Please fix this issue with multiple providers. We are blocked. Does anyone have any workaround to this?

In Azure DevOps above issue makes only like one previously said "it makes a lot of noise in logs" but that is only warnings and pipeline is working ok.

**Comment by AntonChernysh** [comment]
@thejanek True. Though it has to be fixed. This issue should be re-opened.

**Comment by dcfsc** [comment]
Consider the case where I lookup a user using the `azuread` provider, 

```
data "azuread_user" "owner" {
  user_principal_name = "owner@example.com"
}
```

and then apply a role assignment using `azurerm` provider.

```
resource azurerm_role_assignment owner_does_contrib_on_apigw {
  scope                = azurerm_function_app.apigw.id
  role_definition_name = "Contributor"
  principal_id         =  data.azuread_user.owner.object_id
}
```

Currently I believe there is no way to do this, except split the project into two, pull the ids in the first run, store them in remote state, or in a pipeline-specific variable, and the build in the second run.  Not pretty.

**Comment by ttjackott** [comment]
What confuses me is that this warning shows up even **if you only have 1 provider block in the root module**. My child modules don't have any provider blocks in them, so not sure why this warning shows every time.

**Comment by larryclaman** [comment]
I am also seeing this erroneous warning, and I only have 1 provider block in my config.

**Comment by dotnetcanuck** [comment]
> I'd like this to be reopened. Using a single provider with multiple modules should not throw a warning like this. If modules are heavily utilized, it creates a lot of noise in the output window and in Azure Devops pipelines.

@Roshan-Kumar-Microsoft This issue should be re-opened. Like @ztbrumbaugh said, this warning appears when using a single provider in multiple modules, even if there's _only a single provider block_ across all `.tf` files.

In the following example from my pipeline, the warning is erroneous, because there's only one provider block in the entire repo. The whole point of modules is to minimize code duplication - inheriting a provider from the root module is a perfectly valid scenario.

```
├── provider.azurerm =2.15
└── module.VM01
    └── provider.azurerm (inherited)

##[warning]Multiple provider blocks specified in the .tf files in the current working drectory.
```

**Comment by theadzik** [comment]
`├── provider.azurerm ~>2.16.0
├── module.core
│   └── provider.azurerm (inherited)
├── module.serverless
│   └── provider.azurerm (inherited)
└── module.storage
    └── provider.azurerm (inherited)

##[warning]Multiple provider blocks specified in the .tf files in the current working drectory.
`

Terraform v0.12.28

**Comment by sonic1981** [comment]
@Roshan-Kumar-Microsoft  Please re-read this issue and re-open. You have misinterpreted what has been said. I can also confirm this problem. The issue **isn't** that the OP wants multiple provider blocks it's that the OP has **one provider block** but the provider warns that there are multiple even when there aren't. so your response of:

> We are not supporting Multiple provider blocks

doesn't make sense or address the issue being talked about.

**Comment by CaptainStealthy** [comment]
At this point, no one from MSFT has replied to this thread in almost 9 months. It would probably be faster for someone to submit a PR to fix this.

I've done a search of the repo, and came up with two TypeScript files (one being the task itself, and another for tests) that contain the erroneous warning message with the typo.

I'm well-versed in TypeScript, but I know nothing about writing extensions for Azure DevOps. Anyone else have the skill set to help fix this problem?

https://github.com/microsoft/azure-pipelines-extensions/search?q=Multiple+provider+blocks+specified+in+the+.tf+files+in+the+current+working+drectory&unscoped_q=Multiple+provider+blocks+specified+in+the+.tf+files+in+the+current+working+drectory

**Comment by sonic1981** [comment]
@chshrikh Looks like your the person who actually assigned this and the person who closed this (incorrectly, see above) hasn't actually logged into GitHub since January. Can you re-open/re-assign this issue?

**Comment by rami-o-hassan** [comment]
@CaptainStealthy Thanks for getting to the bottom of this. The regex used is very broad. In my case, I get the warning because my provider block has a   skip_**_provider_**_registration attribute. I think the solution is just to make the regex more specific.

```terraform
**provider** "azurerm" {
  version = "~> 2.20"
  features {}
  skip_**provider**_registration = true
}
```

**Comment by CaptainStealthy** [comment]
@rami-o-hassan No worries. I've been too busy to look at creating a pull request for this. I noticed that one got created by someone else (https://github.com/microsoft/azure-pipelines-extensions/pull/852), but it really doesn't fix the problem that we're talking about.

Also, @chshrikh @nadesu @N-Usha, I don't necessarily agree with the `enhancement` label that's been applied to this issue - I would prefer to call this a bug. The issue is still closed as well, and needs to be reopened.

**Comment by rami-o-hassan** [comment]
From a separation of concerns perspective, it shouldn't be really the responsibility of the task to do this check. The task's responsibility is to invoke a TF command. Validating the TF files in order to ensure that the command will work is much bigger of a responsibility. And there is much more to this than just counting the number of the provider blocks. 

My suggestion is to remove this check altogether, and leave it to TF to decide.

**Comment by CaptainStealthy** [comment]
@chshrikh @nadesu @N-Usha The above linked pull request (#852) by @sivapalan fixes this problem, but maintains the current state of the extension, whereby only a single extension *type* (e.g. Azure, AWS, GCP) is supported. But multiple instances of the `azurerm` provider, for example, should not throw this warning.

**Comment by nadesu** [comment]
@CaptainStealthy - Dev who worked on this task earlier is on extended leave, sorry for the delay. We will prioritise it for the coming sprint

**Comment by CaptainStealthy** [comment]
@nadesu Thank you for that...but all you need to do is review that pull request. :)

**Comment by kylelee24** [comment]
Has this been fixed?

**Comment by kgopi1** [comment]
waiting the solution .. getting the same warning in Azure Devops pipeline only and not in the nornmal terraform plan.

**Comment by jmorsecode** [comment]
I feel like this may help clarify and hopefully expedite this issue. I see plenty of examples with one or the other but none directly comparing the old output that Azure clearly is based on and current versions of Terraform:
Terraform v0.12.24:
```
$ terraform providers
.
└── provider.aws

```
Terraform v0.13.6:
```
$terraform providers

Providers required by configuration:
.
└── provider[registry.terraform.io/hashicorp/aws]

Providers required by state:

    provider[registry.terraform.io/hashicorp/aws]

```

These versions are just an example to show that the new output for providers in current and future versions would require more advanced checks than the current Azure code or simply just removing the multiple provider warning and leaving warnings to 'terraform validate'.

**Comment by CaptainStealthy** [comment]
The PR linked to this thread fixes the problem. But no one at Microsoft seems inclined to review it.

**Comment by rudolphjacksonm** [comment]
I've opened a separate issue to draw attention to this as it's irritating to see on every terraform run and I'd like to draw some fresh :eyes: to it. ☝️ Apologies if this is not the right way to go about it, but nobody seems to be reviewing this PR anymore now that it's been closed.

**Comment by ak58588** [comment]
I am getting this error with various terraform versions in Azure DevOps pipeline. **"Multiple provider blocks specified in the .tf files in the current working drectory."** It is extremely annoying. My pipeline gets stuck on this warning and the plan never goes further.
The one who introduced this error message didn't even bother to check its spelling. 
Extremely annoying, this has to be fixed.

**Comment by gdsjerry** [comment]
Also waiting for fix for this. Quite irritating
