### ISSUE TITLE
Problems with init command in the version deployed today

### ISSUE THREAD

**Issue by lfraile** [microsoft/azure-pipelines-extensions#751]
Hello, with the new version deployed today I'm starting to have an error when doing the terraform init:

_2019-12-18T08:20:54.9910580Z [0mThe backend configuration argument "arm_environment" given on the command line
2019-12-18T08:20:54.9910767Z is not expected for the selected backend type._

The line it executes is:
terraform.exe init -backend-config=storage_account_name=XXXX -backend-config=container_name=XXXX -backend-config=key=terraform.xxx.pre.state -backend-config=resource_group_name=XXXX -backend-config=arm_subscription_id=XXXX -backend-config=arm_tenant_id=*** -backend-config=arm_client_id=*** -backend-config=arm_client_secret=*** -backend-config=arm_environment=AzureCloud

My config.tf looks like:
terraform {
  backend "azurerm" {  
  }
}

**Comment by sterowney** [comment]
Same here 👍

**Comment by sebader** [comment]
same here! Exact same pipeline ran without issues last night. Then it did not have the parameter 
`-backend-config=arm_environment=AzureCloud`

**Comment by avaldi** [comment]
Same here. Any workaround? Can't find a way to downgrade to the previous task version.

**Comment by sebader** [comment]
I just also opened a thread in the Dev forums: https://developercommunity.visualstudio.com/content/problem/860529/terraform-task-extension-broken-since-today.html

**Comment by lfraile** [comment]
> 
> 
> Same here. Any workaround? Can't find a way to downgrade to the previous task version.

There is no way to downgrade, as they only updated as a minor version :(

**Comment by rikribbers** [comment]
Looks like version 0.0.139 is failing.

Last seen working version in our environment is 0.0.137


==============================================================================
Task         : Terraform
Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
Version      : 0.0.139
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/AA5j5pf)
==============================================================================

**Comment by chernihiv** [comment]
Similar issue with other tasks, e.g. `terraform plan`

```
2019-12-18T08:53:46.1725665Z [1m[31mError: [0m[0m[1mAn Azure Environment with name "AzureCloud" was not found: autorest/azure: There is no cloud environment matching the name "AZUREAZURECLOUDCLOUD"[0m
2019-12-18T08:53:46.1725768Z 
2019-12-18T08:53:46.1725835Z [0m  on configuration.tf line 1, in provider "azurerm":
2019-12-18T08:53:46.1725927Z    1: provider "azurerm" [4m{[0m
2019-12-18T08:53:46.1726010Z [0m
2019-12-18T08:53:46.1726065Z [0m[0m
```

**Comment by Cloudenius** [comment]
Same here! Unfortunately, it's blocking our releases. I have informed Microsoft via Twitter and will reach out to our internal contacts. Keep you posted.

**Comment by Lahiri** [comment]
Same here. I had a presentation with a customer this morning. Yesterday everything was working and now all is broken. Crazy.

**Comment by mortenlerudjordet** [comment]
This broke all our prod pipelines also.
Please rollback as fast as possible.

**Comment by rll-cloudeon** [comment]
This is breaking our production pipelines - are there any workarounds?

**Comment by Roshan-Kumar-Microsoft** [comment]
Working to fix it

**Comment by mcalnd70** [comment]
+1 here too. I'm thankful I'm not the only one

**Comment by oildriller** [comment]
+1 the same problem here. We have are preparing for an important customer demo tomorow and now we are not able to create releases

**Comment by SadokLadhari** [comment]
+1 the same problem here.
Yesterday my pipeline was working fine and after the upgrade (adding -backend-config=arm_environment=AzureCloud) it failes (exactly in a DEMO) :(

**Comment by Roshan-Kumar-Microsoft** [comment]
Releasing latest version with fix

**Comment by ralphwillgoss** [comment]
I've logged a support issue, as a few of us where chatting on the Dev Forums:
https://developercommunity.visualstudio.com/content/problem/860684/terraform-pipeline-task-is-not-working-anymore-sta.html?inRegister=true

thanks to @Roshan-Kumar-Microsoft, I'll post back on the other thread.

**Comment by rajan-bhaniwal** [comment]
@Roshan-Kumar-Microsoft, Any ETA on when the fix will be rolled out?

**Comment by speedmind** [comment]
Got bitten by this too, with a client demo as well...
@Roshan-Kumar-Microsoft, now that there's a fix, is there anything we can do to get the extension updated on our Azure DevOps organization (Azure DevOps Service) ?

**Comment by mortenlerudjordet** [comment]
Would have been nice if someone at MS can trigger a build and publish of the extension to marketplace.
@Roshan-Kumar-Microsoft

**Comment by dalareo** [comment]
Having a task version to set would be a solution for this "toofasttorelease" problems...

**Comment by mortenlerudjordet** [comment]
Another is to have the option on AzD to set extension updates to manual on a pr extension level

**Comment by Roshan-Kumar-Microsoft** [comment]
Published New version of terraform extension on marketplace ..Please verify it .

**Comment by mortenlerudjordet** [comment]
@Roshan-Kumar-Microsoft , Can see it and it has updated in our AzD. Testing to see if we are good.

**Comment by speedmind** [comment]
> Published New version of terraform extension on marketplace ..Please verify it . If still face any issue let me know

not looking very good...
2019-12-18T12:47:17.0053824Z ##[error]File not found: '/home/vsts/work/_tasks/TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf/0.0.140/src/index.js'

but I'll run a new release just in case...

**Comment by Lahiri** [comment]
> > Published New version of terraform extension on marketplace ..Please verify it . If still face any issue let me know
> 
> not looking very good...
> 2019-12-18T12:47:17.0053824Z ##[error]File not found: '/home/vsts/work/_tasks/TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf/0.0.140/src/index.js'
> 
> but I'll run a new release just in case...

I get exactly the same error.

**Comment by dalareo** [comment]
Me too
##[error]File not found: '/home/vsts/work/_tasks/TerraformInstaller_a4789e5d-f6e8-431f-add9-379d640a883c/0.0.17/src/index.js'

**Comment by speedmind** [comment]
Yup, it's the same with a new release...

**Comment by rajan-bhaniwal** [comment]
2019-12-18T12:48:54.4748406Z ##[error]File not found: '\TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf\0.0.140\src/index.js'
Same here

**Comment by Roshan-Kumar-Microsoft** [comment]
Give me few minute looking into it

**Comment by ralphwillgoss** [comment]
Got a new error 
`##[error]File not found: '/home/vsts/work/_tasks/TerraformInstaller_a4789e5d-f6e8-431f-add9-379d640a883c/0.0.17/src/index.js'`

**Comment by mortenlerudjordet** [comment]
Probably have to uninstall and reinstall. Have seen some strange behavior updating the task I have developed myself

**Comment by dalareo** [comment]
> Probably have to uninstall and reinstall. Have seen some strange behavior updating the task I have developed myself

I did it without success

**Comment by oildriller** [comment]
2019-12-18T12:53:01.3195712Z ##[error]File not found: 'D:\a\_tasks\TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf\0.0.140\src/index.js'

Same error observed here

**Comment by dhabierre** [comment]
I have exactly the same issue today...

```
2019-12-18T13:08:29.8921038Z ##[debug]Evaluating condition for step: 'Terraform init'
2019-12-18T13:08:29.8921555Z ##[debug]Evaluating: succeeded()
2019-12-18T13:08:29.8921712Z ##[debug]Evaluating succeeded:
2019-12-18T13:08:29.8921923Z ##[debug]=> True
2019-12-18T13:08:29.8922146Z ##[debug]Result: True
2019-12-18T13:08:29.8922348Z ##[section]Starting: Terraform init
2019-12-18T13:08:29.8926248Z ==============================================================================
2019-12-18T13:08:29.8926687Z Task         : Terraform
2019-12-18T13:08:29.8926760Z Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
2019-12-18T13:08:29.8926867Z Version      : 0.0.140
2019-12-18T13:08:29.8926916Z Author       : Microsoft Corporation
2019-12-18T13:08:29.8927011Z Help         : [Learn more about this task](https://aka.ms/AA5j5pf)
2019-12-18T13:08:29.8927074Z ==============================================================================
2019-12-18T13:08:29.9189744Z ##[error]File not found: '/home/admin-vm/agent/_work/_tasks/TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf/0.0.140/src/index.js'
2019-12-18T13:08:29.9205359Z ##[debug]System.IO.FileNotFoundException: File not found: '/home/admin-vm/agent/_work/_tasks/TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf/0.0.140/src/index.js'
File name: '/home/admin-vm/agent/_work/_tasks/TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf/0.0.140/src/index.js'
   at Microsoft.VisualStudio.Services.Agent.Util.ArgUtil.File(String fileName, String name)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2019-12-18T13:08:29.9206803Z ##[section]Finishing: Terraform init
```

Thanks!

**Comment by lfraile** [comment]
Same error with file not found here, still not able to deploy :(

**Comment by dhabierre** [comment]
It is really strange that an upgrade kills the previous version... it is dangerous... pipeline is not immutable.

**Comment by Lahiri** [comment]
> It is really strange that an upgrade kills the previous version... it is dangerous... pipeline is not immutable.

I agree, we should have more control on task versioning, so that we can rollback if problems like this come out.

**Comment by PavelPikat** [comment]
Got bitten by this too :(
It will be a lesson to all that 3rd party plugin in Azure DevOps should not be relied upon. It probably makes sense to invoke Terraform from in-house scripts and not custom extensions.

**Comment by CharlesAtDCube** [comment]
##[error]File not found: 'D:\a_tasks\TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf\0.0.140\src/index.js' Same here

**Comment by joakimhellum** [comment]
It looks like current release (`0.1.5`) contains `node_modules` and TypeScript source files, but not compiled javascript files (`index.js`). Probably new version need to be published that includes all necessary files.

In addition the task is still setting incorrect provider arguments ref. `setupBackend` function https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/Terraform/Src/Tasks/TerraformTaskV1/src/azure-terraform-command-handler.ts#L17-L20 and https://www.terraform.io/docs/providers/azurerm/index.html (for example, `arm_subscription_id` should be `subscription_id`, whereas `ARM_SUBSCRIPTION` environment variable can also be set).

**Comment by tomaszgawlik** [comment]
it would be great to be able control whole task version, not only major part of it

**Comment by FireStormHR** [comment]
> It looks like current release (`0.1.5`) contains `node_modules` and TypeScript source files, but not compiled javascript files (`index.js`). Probably new version need to be published that includes all necessary files.
> 
> In addition the task is still setting incorrect provider arguments ref. `setupBackend` function https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/Terraform/Src/Tasks/TerraformTaskV1/src/azure-terraform-command-handler.ts#L17-L20 and https://www.terraform.io/docs/providers/azurerm/index.html (for example, `arm_subscription_id` should be `subscription_id`, whereas `ARM_SUBSCRIPTION` environment variable can also be set).

@RoshanKumarMicrosoft Is this any help? Can you maybe escalate the problem because the service is already down for over 5 hours

**Comment by Roshan-Kumar-Microsoft** [comment]
Will release extension in a hour ...Just doing testing

**Comment by chemapolo** [comment]
We are facing the same issue during the last 5 hours...

**Comment by smushtaq** [comment]
> Will release extension in a hour ...Just doing testing

fingers crossed. have a demo in half an hr.

**Comment by afouilleul** [comment]
It looks like CI tests have failed since October ...

**Comment by Cloudenius** [comment]
I see version 0.1.7 was released! Testing now... (Not sure what happened with version 0.1.6?)

**Comment by speedmind** [comment]
Same error as before...
2019-12-18T15:00:23.5926377Z ##[error]File not found: '/home/vsts/work/_tasks/TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf/0.0.140/src/index.js'

**Comment by dhabierre** [comment]
Are you sure that a new version is published?

```
2019-12-18T14:59:39.4970695Z ==============================================================================
2019-12-18T14:59:39.4970950Z Task         : Terraform
2019-12-18T14:59:39.4971023Z Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
2019-12-18T14:59:39.4971125Z Version      : 0.0.140
2019-12-18T14:59:39.4971179Z Author       : Microsoft Corporation
2019-12-18T14:59:39.4971274Z Help         : [Learn more about this task](https://aka.ms/AA5j5pf)
2019-12-18T14:59:39.4971342Z ==============================================================================
```

**Comment by Cloudenius** [comment]
> Are you sure that a new version is published?
> 
> ```
> 2019-12-18T14:59:39.4970695Z ==============================================================================
> 2019-12-18T14:59:39.4970950Z Task         : Terraform
> 2019-12-18T14:59:39.4971023Z Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
> 2019-12-18T14:59:39.4971125Z Version      : 0.0.140
> 2019-12-18T14:59:39.4971179Z Author       : Microsoft Corporation
> 2019-12-18T14:59:39.4971274Z Help         : [Learn more about this task](https://aka.ms/AA5j5pf)
> 2019-12-18T14:59:39.4971342Z ==============================================================================
> ```

I think you're using this extension, right? https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform

We are talking about the official extension from Microsoft, which is now in 0.1.7: https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks

**Comment by smushtaq** [comment]
same as before. Using the official Micrososft version

**Comment by rikribbers** [comment]
0.0.140 was failing previously... I am awaiting version 0.0.141

**Comment by dhabierre** [comment]
> We are talking about the official extension from Microsoft, which is now in 0.1.7

I use this one too.

**Comment by chernihiv** [comment]
![image](https://user-images.githubusercontent.com/7537522/71097431-9ffbcd80-21b8-11ea-84d5-0b463ca085ae.png)

**Comment by Cloudenius** [comment]
Ah, I see now. The extension version is different (0.1.7) from the Terraform task version (0.0.140).

**Comment by smushtaq** [comment]
@Roshan-Kumar-Microsoft Its still the same error. Please restore the old working version and then release the new one at a later date with thorough testing. 

Thanks

**Comment by dhabierre** [comment]
@Roshan-Kumar-Microsoft : as requested by @smushtaq, is it possible to release the rollback? Thanks.

**Comment by ralphwillgoss** [comment]
> > Are you sure that a new version is published?
> > ```
> > 2019-12-18T14:59:39.4970695Z ==============================================================================
> > 2019-12-18T14:59:39.4970950Z Task         : Terraform
> > 2019-12-18T14:59:39.4971023Z Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
> > 2019-12-18T14:59:39.4971125Z Version      : 0.0.140
> > 2019-12-18T14:59:39.4971179Z Author       : Microsoft Corporation
> > 2019-12-18T14:59:39.4971274Z Help         : [Learn more about this task](https://aka.ms/AA5j5pf)
> > 2019-12-18T14:59:39.4971342Z ==============================================================================
> > ```
> 
> Are you using the official Microsoft task?
> 
> We are talking about the official extension from Microsoft, which is now in 0.1.7: https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks

I think you are looking at the wrong one

**Comment by ianpurvis1976** [comment]
This issue is hitting me hard today.

**Comment by SadokLadhari** [comment]
@Roshan-Kumar-Microsoft as said by @smushtaq Please restore the old working version.

**Comment by chshrikh** [comment]
sorry for the inconvenience, we are working on the fix and will soon publish the new version

**Comment by afouilleul** [comment]
After unistall and reinstall version 0.1.7, different error :
```
2019-12-18T15:24:01.2002189Z Downloading task: TerraformInstaller (0.0.17)
2019-12-18T15:24:01.2803003Z ##[warning]Failed to download task 'TerraformInstaller'. Error No task definition found matching ID a4789e5d-f6e8-431f-add9-379d640a883c and version 0.0.17. You must register the task definition before uploading the package.
2019-12-18T15:24:01.2820066Z ##[warning]Back off 10.617 seconds before retry.
2019-12-18T15:24:11.9348198Z ##[warning]Failed to download task 'TerraformInstaller'. Error No task definition found matching ID a4789e5d-f6e8-431f-add9-379d640a883c and version 0.0.17. You must register the task definition before uploading the package.
2019-12-18T15:24:11.9348981Z ##[warning]Back off 16.178 seconds before retry.
2019-12-18T15:24:28.1482182Z ##[error]No task definition found matching ID a4789e5d-f6e8-431f-add9-379d640a883c and version 0.0.17. You must register the task definition before uploading the package.
2019-12-18T15:24:28.1491678Z ##[section]Finishing: Initialize job
```

**Comment by chshrikh** [comment]
we are published the new version of extension, please let us know if it works for you all

**Comment by turbut** [comment]
0.1.8 did the trick

**Comment by Cloudenius** [comment]
Version 0.1.8 seems to be live indeed. Looking into it!

**Comment by FireStormHR** [comment]
PROBLEM SOLVED, THANKS @chshrikh and @Roshan-Kumar-Microsoft

**Comment by chshrikh** [comment]
Thanks @Ajay-MS and @Roshan-Kumar-Microsoft for quick actions

**Comment by lfraile** [comment]
It's working!!!! thanks @Ajay-MS and @Roshan-Kumar-Microsoft

**Comment by speedmind** [comment]
Working here as well on extension v0.1.8 (task v0.0.142).

Many thanks to all and @Roshan-Kumar-Microsoft for the live updates...

**Comment by SadokLadhari** [comment]
Thanks @chshrikh , it works now with the latest version 0.1.8 
![image](https://user-images.githubusercontent.com/1139512/71099790-23ff8680-21b4-11ea-8609-c94b4b231443.png)

**Comment by mortenlerudjordet** [comment]
Also fixed on our end

**Comment by dhabierre** [comment]
All rocks!
Thanks for the fixing!

**Comment by rikribbers** [comment]
Thanks for fixing, it is working for us.

I noticed another error in the terraform plan task. What I make of it is that the Azure DevOps Task does a terraform version command to output the version after a terraform plan command. This gives the output below. It complains about "too many command line arguments." Is this related to this or something else?

Output:

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
/usr/local/bin/terraform version
Terraform v0.12.12
+ provider.azuread v0.7.0
+ provider.azurerm v1.39.0
+ provider.random v2.2.1

Your version of Terraform is out of date! The latest version
is 0.12.18. You can update by downloading from www.terraform.io/downloads.html
**Too many command line arguments. Configuration path expected.
Terraform couldn't read the given file as a state or plan file.**

The errors while attempting to read the file as each format are
shown below.

State read error: Error loading statefile: open /azp/agent/_wor

**Comment by DaveWall77** [comment]
Did not fix our issue. We still receive the same error with latest version of Terraform Task. v0.1.8, but our task version shows Version: 0.0.140, instead of 0.0.142 as reported above.

**Comment by mcalnd70** [comment]
Seemed to be working ok last night when I tried it again and caught up with some backed up releases from the day

Will their be a post-mortem on this one? My boss is asking what happened. Other than something broke overnight on 17th/18th December, I don't know what else to report back

**Comment by dhabierre** [comment]
@mcalnd70, a patch of the Terraform task has been releases yesterday but it was buggy.

Currently, patchs or minor versions seem to be autoloaded by AzDevOps (you can select only major version: 0.*, 1.*, etc). If the version is buggy, the pipeline becomes down.

Patched tasks or minor releases should not beautomatically loaded. With the current behavior of AzDevOps, this problem can occur in future.

**Comment by DaveWall77** [comment]
yes, working now. 0.0.142
