### ISSUE TITLE
index.js File not found in version 0.0.140 of Terraform Extension for Azure DevOps 

### ISSUE THREAD

**Issue by dhaworth** [microsoft/azure-pipelines-extensions#753]
Good morning,

[A commit to the Terraform pipeline task](https://github.com/microsoft/azure-pipelines-extensions/commit/54d88ccda05e1f37b7dcfcd7504020f3a7ea1b4f) for ADO seems to have broken our pipelines that use that task. Wondering if others are seeing the same issue. Thanks.

```
##[section]Starting: Terraform : init
==============================================================================
Task         : Terraform
Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
Version      : 0.0.140
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/AA5j5pf)
==============================================================================
##[error]File not found: 'C:\CF-INFRA-BUILD2\_work\_tasks\TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf\0.0.140\src/index.js'
##[section]Finishing: Terraform : init
```
cc: @Roshan-Kumar-Microsoft

**Comment by DaveWall77** [comment]
We're waiting on a fix for this as well.

**Comment by mortenlerudjordet** [comment]
There can be some caching problems with previous bad version.
Just do a uninstall of the extension and re-add it through market place.

Make sure no pipelines are running that is using the task during the process.

**Comment by DaveWall77** [comment]
uninstalled/reinstalled 0.0.142 works. thanks

**Comment by liamfoneill** [comment]
@Roshan-Kumar-Microsoft is there a reason that V1 of the task keeps getting patched rather than create a new version? 

There are lots of people depending on this task and have no way of protecting themselves from a broken version of the task being added to V1 (as what seemed to happen here)

**Comment by dhaworth** [comment]
This is working for us now with the 0.0.142 version. Agree with @liamfoneill that appropriate versioning may have helped, though I don't know that the Azure Marketplace allows for designating task versions on a granular enough basis to fully protect against this.

I'm going to close the issue since the problem is fixed. Thanks @Roshan-Kumar-Microsoft
