### ISSUE TITLE
Terraform Cloud Support

### ISSUE THREAD

**Issue by sheldonhull** [microsoft/azure-pipelines-extensions#754]
Terraform Blog announced upcoming improvements with the azure pipelines extensions for Terraform that would support the following types of commands: 

1. Terraform Cloud Backend
2. Create new tfe_workspace, variables, and more.
3. Initiating remote run, plan, apply. 

I've been searching issues, announcements, community discussion, and even commits, but am having difficulty in finding anything on eta, progress, or issues to watch on this. 

I need ways to improve the terraform cloud workflow and am hoping azure pipelines can offer this, so I can automate workspace management. 

Can someone provide some linked issues on implementation of Terraform Cloud support with the terraform extension so I can be more aware of the progress of this new feature?

**Comment by RoopeshNair** [comment]
@sheldonhull  - can you point us to the blog? are you referring to [this extension](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks) or some other extension?

**Comment by sheldonhull** [comment]
> You can sign up for the preview here. Once it's generally available, you will be able to to get started by accessing the Azure DevOps marketplace and searching for the Terraform task published by Microsoft. 

This is the [blog post](https://www.hashicorp.com/blog/announcing-azure-devops-support-for-terraform-cloud-and-enterprise/) I'm referring to. Since it was the microsoft terraform task, not a new one being created by them, I thought I'd find the updates on progress here.

**Comment by RoopeshNair** [comment]
@sheldonhull  - Thanks for the pointer. I would recommend you to connect with the blog post author.
