### ISSUE TITLE
tfs:feed returns wrong endpointurl

### ISSUE THREAD

**Issue by renevanosnabrugge** [microsoft/azure-pipelines-extensions#755]
Hi,

I am using the endpoint tfs:feed in my extension. The task should return the endpointurl to the feed, That endpoint url I also use in getting packages and release views. Since the introduction of Project Scoped feeds, the task does not return the project scoped feeds. I feel that the endpointurl should reflect the projectID as well.

https://github.com/microsoft/azure-pipelines-extensions/blob/master/docs/authoring/endpoints/tfs-vsts-endpoints.md

Th issue of "my task"
https://github.com/renevanosnabrugge/vsts-promotepackage-task/issues/38

**Comment by chshrikh** [comment]
@renevanosnabrugge could you please open issue at - https://github.com/microsoft/azure-pipelines-tasks/issues, your question is related to task lib / platform

**Comment by chshrikh** [comment]
this is not correct forum for this issue
