### ISSUE TITLE
[Terraform task] stuck on user input

### ISSUE THREAD

**Issue by algattik** [microsoft/azure-pipelines-extensions#757]
Running Terraform task with a plan where a variable does not have a default value, and is not provided on the command line, causes the task to get stuck waiting for user input (which there is no way to provide).

The task should pass `-input=false` to plan and apply commands.

**Comment by Roshan-Kumar-Microsoft** [comment]
@algattik If I am understanding right you have option to pass additional argument ? Can you please share the screenshots Not able to get complete issue

**Comment by algattik** [comment]
Hi @Roshan-Kumar-Microsoft, the issue is the following: if in your variables.tf you define a variable without a default value, and in the plugin configuration you forget to pass a value for that variable, the task just hangs because terraform asks for a interactive input.

Expected behavior: the task should fail immediately
