### ISSUE TITLE
SPNCreation.ps1 does not work with new "Az" module

### ISSUE THREAD

**Issue by qJake** [microsoft/azure-pipelines-extensions#758]
In a fresh environment, running this script:

https://github.com/microsoft/azure-pipelines-extensions/blob/master/TaskModules/powershell/Azure/SPNCreation.ps1

Does not work with [Az PowerShell Module v3.2.0](https://github.com/Azure/azure-powershell/releases/tag/v3.2.0-December2019) installed.

The following error occurs:

> Script requires AzureRM modules to be present. Obtain AzureRM from https://github.com/Azure/azure-powershell/releases. Please refer https://github.com/Microsoft/azure-pipelines-tasks/blob/mas
ter/Tasks/AzureResourceGroupDeploymentV2/README.md for recommended AzureRM versions.

**This is an enhancement request to support the latest version (3.2.0) of the Az PowerShell module.** Users should not have to install an older Azure PowerShell module to run this script.

## Reproduce

1. Clean environment (i.e. Windows Sandbox)
2. Install Az module: `Install-Module -Name Az -Repository PSGallery -Force`
3. Answer "Yes" to NuGet prompt
4. Restart PS environment / ISE
5. Open (or copy and paste) SPNCreation.ps1 and execute

## Environment

Windows 10 v1909 (18363.535)
PowerShell v5.1.18362.145 (Edition: Desktop, Build: 10.0.18362.145)
Azure Retail (PAYG) Subscription

**Comment by arjgupta** [comment]
I have created a PR for this here: https://github.com/microsoft/azure-pipelines-extensions/pull/772/files
