### ISSUE TITLE
IIS Web App Deployment Using WinRM for TFS 2017 RTM

### ISSUE THREAD

**Issue by randy-wong** [microsoft/azure-pipelines-extensions#759]
Hi all,

I tried to install IIS Web App Deployment Using WinRM but I kept getting the error "task.json file was not found in contribution". I found out that the version of TFS (TFS 2017 RTM / TFS Version 15.105.25910.0) that I am isn't compatible with the marketplace version. I also tried manually downloading the latest version here and it is different (looks buggy) from the version that I have on my preproduction environment. 

Aside from upgrading my environment, does anyone know of any alternatives or a lower version of this vNext custom task that I can install?

Thanks,
Randy

**Comment by arjgupta** [comment]
you can try to download and install an older version of the extension from here: https://github.com/microsoft/azure-pipelines-extensions/releases
