### ISSUE TITLE
Terraform plan log adds time references at the beginning of each line

### ISSUE THREAD

**Issue by wenesak** [microsoft/azure-pipelines-extensions#763]
Is hard to review the generated plan 
Example:

![image](https://user-images.githubusercontent.com/28111142/72396786-72e10300-3703-11ea-9dc3-e56f4d883144.png)

Here is an output plan from another Terraform extension:

![image](https://user-images.githubusercontent.com/28111142/72396989-0e727380-3704-11ea-8633-35dddf0211b2.png)

Please clean up the output

**Comment by Roshan-Kumar-Microsoft** [comment]
@wenesak  Can you please run same terraform command in your command prompt(Terminal) Does it produce different log ? If this will the case we will try to incorporate this .

**Comment by Bouke** [comment]
The garbled output you're seeing are control characters; those control things like color. So what terraform is doing is showing `+` as green and `-` as red. However due to some mismatch, the colors aren't applied and the control characters shown as-is.

**Comment by wenesak** [comment]
@Bouke 

Thanks for the tip, I did updated the arguments to include -no-color and my terraform plan log now is easy to read 

@Roshan-Kumar-Microsoft 
Boukes suggestion worked fine for my issue
