### ISSUE TITLE
TerraformTask without need for service connection

### ISSUE THREAD

**Issue by richardgavel** [microsoft/azure-pipelines-extensions#764]
I would like to use TerraformTask on private agents I have already running inside AWS. Because they are in AWS, they do not need a service connection, they use the credentials implicit from the AWS instance they are running on. However, I can't use the task without providing a provider, and when selecting aws, the service connection is required.

**Comment by Roshan-Kumar-Microsoft** [comment]
@richardgavel  This is by design. Provider is necessary to run this task. I agreed with you this can be enhancement but due to other priority work we will not able to pick this now.

**Comment by derhally** [comment]
I ran into this today.  We do not require a AWS connection to specified because the agent assumes a role.
