### ISSUE TITLE
Add support for -detailed-exitcode in terraform plan

### ISSUE THREAD

**Issue by robyf** [microsoft/azure-pipelines-extensions#768]
From the terraform plan command documentation:
* `-detailed-exitcode` - Return a detailed exit code when the command exits. When provided, this argument changes the exit codes and their meanings to provide more granular information about what the resulting plan contains:
  *    0 = Succeeded with empty diff (no changes)
  *    1 = Error
  *    2 = Succeeded with non-empty diff (changes present)

If this status code would be made available as a variable (something as changesPresent with boolean value) it would be possible to skip the next apply step completely. In our case we have an approval step between apply and plan and every time we have to apply or deny it even when there are no changes.

**Comment by mericstam** [comment]
fixed in PR https://github.com/microsoft/azure-pipelines-terraform/pull/11 in new repo.  Release will be done in the next days.
