### ISSUE TITLE
Terraform init fails with file not found issue

### ISSUE THREAD

**Issue by sriramdasbalaji** [microsoft/azure-pipelines-extensions#792]
Hi,

When I run Terraform init in my release pipelines task failed with the following error
File not found: 'D:\a\_tasks\TerraformTaskV1_fe504acc-6115-40cb-89ff-191386b5e7bf\0.0.140\src/index.js

![image](https://user-images.githubusercontent.com/13716984/76593999-da59da00-651d-11ea-8538-cdea7b08207d.png)

**Comment by Roshan-Kumar-Microsoft** [comment]
@sriramdasbalaji  Can you please clean task file from agent and try to re-run it ?

**Comment by jeffpatton1971** [comment]
We are experiencing this issue as well, what we have noted is that the task runs find on Windows Server 2016 but fails with Windows Server 2019. It appears the underlying issue has something to do with mklink. Initially we thought perhaps mklink wasn't available in 2019, but it was, then we attempted to replicate the issue, but running mklink manually created the directory symlink just fine. Additionally we looked at disabled UAC on the server, but that had no impact as well, finally having the agent run as local admin we were unable to get it to work.

I am happy to hop on a call and show you this in realtime if you have time.

Thanks!

**Comment by jeffpatton1971** [comment]
Also this appears to potentially be a bug.

**Comment by sriramdasbalaji** [comment]
Hi @jeffpatton1971 ,

The issue got resolved for me after Uninstalling and reinstalling the Terraform extension.

**Comment by jeffpatton1971** [comment]
@sriramdasbalaji can you elaborate on this at all? How would that resolve the issue? Does the extension not know how to update itself?

**Comment by sriramdasbalaji** [comment]
Hi @jeffpatton1971 ,

Yes, In my Organization it didn't get updated automatically to latest version. PFB Image for your reference
![image](https://user-images.githubusercontent.com/13716984/78034431-5ad56300-7385-11ea-98d4-690ed4a08b64.png)

On Dec 18 it's updated to 0.1.7. But On the same day 0.1.8 also published 
![image](https://user-images.githubusercontent.com/13716984/78034585-8f491f00-7385-11ea-85dc-d8df77c9ef54.png)

Which didn't get updated in my account?

**Comment by jeffpatton1971** [comment]
@Roshan-Kumar-Microsoft can you confirm what the current release version is? I have the same version that @sriramdasbalaji appears to have and i'm facing the issue that i described above.

**Comment by mericstam** [comment]
@jeffpatton1971 @sriramdasbalaji. I will close this Issue. If you feel it is incorrect please reopen it.
