### ISSUE TITLE
"Waiting for console output from an agent...", but no console logs

### ISSUE THREAD

**Issue by tscully49** [microsoft/azure-pipelines-extensions#805]
Often times when we are using the apply action from the extension, we don't see any terraform logs but we only see "Waiting for console output from an agent...".  We aren't sure if it's something we are doing wrong, but I'm wondering if this is normal behavior.  I would expect to see logs as terraform outputs them, but sometimes we see logs and other times we don't.  Sometimes it takes until the task is done for logs to show up.  Is there a way to see terraform logs as they pop up?  We will often also see a "Warning!" pop up but no logs.  Again, I'm not sure if this is due to the extension, something we are doing wrong, or the pipeline runner, but I thought this would be a good place to start the investigation.  

Example screenshot: 
![image](https://user-images.githubusercontent.com/5360594/79379161-0e148f00-7f24-11ea-9409-90cbd82287b7.png)

**Comment by eaarora-ms** [comment]
Hi @tscully49 ,
This is normal behavior. Normally the logs pop up after the completion of the pipeline. If you want to see detailed logs please set "system.debug" as true in pipeline variables and re-run the pipeline. Please comment if you have any other question.
