### ISSUE TITLE
"[warning]Multiple provider blocks specified" even if 2nd provider is simply "random"

### ISSUE THREAD

**Issue by larryclaman** [microsoft/azure-pipelines-extensions#824]
I'm using a single cloud provider (AzureRM), but I'm also using the terraform random service.   The Azure DevOps Terraform task is throwing the error "[warning]Multiple provider blocks specified" even though I only have one real provider.
While I realize this is a spurious warning and it doesn't seem to affect functionality, it could cause unnecessary time to be spent by developers trying to chase down why this warning is being thrown.

---
terraform providers
.
├── provider.azurerm
└── provider.random

**Comment by Roshan-Kumar-Microsoft** [comment]
This is by design .

**Comment by richardgavel** [comment]
@Roshan-Kumar-Microsoft Can you clarify what you mean by "we are only supporting one provider block". Under what scenarios it is possible something won't work with multiple?
