### ISSUE TITLE
Link in Azure DevOps Task is incorrect

### ISSUE THREAD

**Issue by wesleycamargo** [microsoft/azure-pipelines-extensions#828]
When you click on the task help, the link to documentation it's incorrect.

![image](https://user-images.githubusercontent.com/897126/84302156-46eb7180-ab2b-11ea-91e7-9fd9642646b6.png)

**Comment by Roshan-Kumar-Microsoft** [comment]
Updated link and fixed https://aka.ms/iiswebappdeploydeprecatedreadme
