### ISSUE TITLE
Terraform Apply stalling out

### ISSUE THREAD

**Issue by bkarlen** [microsoft/azure-pipelines-extensions#840]
My tf configuration is correct, this was working until friday morning, and now it just stalls until the build agent cancels it. 

data.azurerm_resource_group.rg: Refreshing state...
azurerm_log_analytics_workspace.lawsql: Creating...
azurerm_storage_account.sasql: Creating...
azurerm_log_analytics_workspace.lawsql: Creation complete after 4s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourcegroups/rg-data-staging/providers/microsoft.operationalinsights/workspaces/lawsql-staging]
azurerm_storage_account.sasql: Still creating... [10s elapsed]
azurerm_storage_account.sasql: Creation complete after 20s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg-data-staging/providers/Microsoft.Storage/storageAccounts/sasqlsecuritystaging]
azurerm_storage_container.vulnerabilitycontainer: Creating...
azurerm_sql_server.FINPACKPlusServer: Creating...
azurerm_storage_container.vulnerabilitycontainer: Creation complete after 0s [id=https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx.blob.core.windows.net/vulnerabilityscanscontainer]
azurerm_sql_server.FINPACKPlusServer: Still creating... [10s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [20s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [30s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [40s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [50s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [1m0s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [1m10s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [1m20s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [1m30s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [1m40s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [1m50s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [2m0s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [2m10s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [2m20s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [2m30s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [2m40s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [2m50s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [3m0s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [3m10s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [3m20s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [3m30s elapsed]
azurerm_sql_server.FINPACKPlusServer: Still creating... [3m40s elapsed]
...
It just continues until the build agent cancels the job.

**Comment by AmrutaKawade** [comment]
which terraform version are you using and which provider? if possible can you share tf configuration?

**Comment by bkarlen** [comment]
this was resolved, the issue was that the azure cache for creating the
server with the same name had it registered but was not creating nor
destroying it.

**Comment by AmrutaKawade** [comment]
It's nice to hear that your issue is resolved now. Closing this issue
