### ISSUE TITLE
Error while installing Terraform on on prem TFS 2017

### ISSUE THREAD

**Issue by uttaradeshmukh** [microsoft/azure-pipelines-extensions#843]
Following errors were found in endpoint contributions: Authentication schemes ms.vss-endpoint.endpoint-auth-scheme-JWT, are not valid

I am trying to install Terraform on my on premise TFS 2017 update 2. but while installing I get the above error.

![image](https://user-images.githubusercontent.com/69590961/90027875-a5250400-dcd6-11ea-8466-47b47a9cd968.png)

**Comment by chshrikh** [comment]
this is not supported with TFS 2017 U2
