### ISSUE TITLE
Upgrading to terraform 0.13

### ISSUE THREAD

**Issue by paddywood** [microsoft/azure-pipelines-extensions#847]
Since upgrading to the latest version of terraform 0.13, my pipelines are failing at the terraform plan step.

My pipeline fails with the following error:

**Could not load plugin**

On the next line in the pipeline logs:

**Plugin reinitialization required. Please run "terraform init".**

Terraform is initialized, and downgrading the terraform version to 0.12.29 fixes the issue.

TBH I am not sure if this is a problem with the extension or not, but just really asking if anyone else is experiencing anything similar....?

**Comment by AmrutaKawade** [comment]
can you try to use terraform init task before plan command?

**Comment by paddywood** [comment]
@AmrutaKawade. Thanks for the reply. I did run the terraform init. I solved the problem by destroying all my resources and deleting the remote storage. I then re ran the terraform and it worked as expected.
Cheers
