### ISSUE TITLE
"features": required field is not set

### ISSUE THREAD

**Issue by julienym** [microsoft/azure-pipelines-extensions#850]
Az DevOps TF Extension: 0.0.142
Terraform 0.12.24
AzureRM provider: tested on 2.0.0, 2.9.0, 2.23.0

My code use an empty features block as required since 2.0.0+
But I get the error: "features": required field is not set

**Comment by AmrutaKawade** [comment]
For which command are you getting this error?

**Comment by julienym** [comment]
On the plan phase. I just tested with a new state file and its working, seam like there is a bug with our tfstate file... Any suggestion ?

**Comment by AmrutaKawade** [comment]
How do you make sure that tfstate file is updated with latest state of your infra?

**Comment by julienym** [comment]
![image](https://user-images.githubusercontent.com/10652969/92632468-0de4a980-f2a0-11ea-9da8-aaed2a656a6a.png)
The diff. in tfstates are mainly in the modules... which could have changed since the beginning...

I will try a TF refresh

**Comment by julienym** [comment]
Refresh doesn't work.... :(

**Comment by julienym** [comment]
A refresh + adding/modifying the state works:
**"module": "module.keyvault",**
"mode": "data",
"type": "azurerm_resource_group",
"name": "this",
**"provider": "module.keyvault.provider.azurerm",**

I guess we change/move this into a module and that created the problem...
