### ISSUE TITLE
Docs say the Terraform Installer Tool's input key is "Version", when it is in fact "terraformVersion"

### ISSUE THREAD

**Issue by DoubleLoopAlex** [microsoft/azure-pipelines-extensions#881]

**Comment by AmrutaKawade** [comment]
Task description itself mentions that this task is for downloading specific version of terraform

and more info text specifies its version of terraform. I don't this its an issue. 

![image](https://user-images.githubusercontent.com/65217380/98914503-c58b7700-24ee-11eb-943b-064cfddbc461.png)
