### ISSUE TITLE
azdo terraofrm task: update deprecated arm warnings 

### ISSUE THREAD

**Issue by marchesir** [microsoft/azure-pipelines-extensions#882]
Hi,

AZDO terraform task (task: TerraformTaskV1@0) for azure has deprecated warnings for some time now.
["arm_subscription_id": [DEPRECATED] `arm_subscription_id` has been replaced by `subscription_id`
["arm_tenant_id": [DEPRECATED] `arm_tenant_id` has been replaced by `tenant_id`
["arm_client_id": [DEPRECATED] `arm_client_id` has been replaced by `client_id`
["arm_client_secret": [DEPRECATED] `arm_client_secret` has been replaced by `client_secret`

https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/Terraform/Src/Tasks/TerraformTaskV1/src/azure-terraform-command-handler.ts
these 4 lines need updating:
this.backendConfig.set('**arm_subscription_id**', tasks.getEndpointDataParameter(backendServiceName, "subscriptionid", true));
this.backendConfig.set('**arm_tenant_id**', tasks.getEndpointAuthorizationParameter(backendServiceName, "tenantid", true));
this.backendConfig.set('**arm_client_id**', tasks.getEndpointAuthorizationParameter(backendServiceName, "serviceprincipalid", true));
this.backendConfig.set('**arm_client_secret**', tasks.getEndpointAuthorizationParameter(backendServiceName, "serviceprincipalkey", true));

what is the process to submitt a pr to get the task updated?

regards 

Richard Marchesi

**Comment by AmrutaKawade** [comment]
there is already PR raised for this https://github.com/microsoft/azure-pipelines-extensions/pull/863. but it would break for the users who are using older version of terraform < 0.12

**Comment by marchesir** [comment]
@AmrutaKawade great thanks, is it likely to get done soon?

**Comment by aristosvo** [comment]
@AmrutaKawade Can you please look at #889? It is solving this problem, but as it is a new version previous versions can use that version instead.

**Comment by artur-carvalho** [comment]
Do you know when this new version will be available?

Will this also solve the skip credentials validation warning?

`Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider`

**Comment by marchesir** [comment]
update:
terraform 0.15 will now break the extension:
https://www.terraform.io/upgrade-guides/0-15.html
althougth terraform init -reconfigure will tell terraform to replace old names with new ones.

**Comment by marchesir** [comment]
refer to ticket  https://github.com/microsoft/azure-pipelines-extensions/pull/863
