### ISSUE TITLE
Unable to detect if there are changes in Terraform

### ISSUE THREAD

**Issue by BlueBasher** [microsoft/azure-pipelines-extensions#886]
It is not possible using the Terraform Task to determine if there are infrastructural changes that need to be applied.
This PR #856 fixes that.

**Comment by CaptainStealthy** [comment]
This is awesome @BlueBasher, thanks so much!

Hopefully this PR gets looked at soon!

**Comment by BlueBasher** [comment]
Hi @AmrutaKawade Any update on this? It's been a long time and the PR has been ready to be merged all that time.
It's a super small change and will help lots of people automate their Terraform deployments even better.

**Comment by mericstam** [comment]
resolved by https://github.com/microsoft/azure-pipelines-terraform/pull/11
release of new version the next few days
