### ISSUE TITLE
"ServiceNow Change Management" - cannot be used as Environment gate on Azure Devops Server 2020

### ISSUE THREAD

**Issue by AThomsen** [microsoft/azure-pipelines-extensions#890]
The extension [ServiceNow Change Management](https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.vss-services-servicenowchangerequestmanagement) can be used as an [environment gate](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass).

This works in Azure Pipelines (cloud) but not in Azure Devops Server 2020 . In ADO-Server ServiceNow gates shows up in Classic Pipelines but not in the Environment "Add check" list.

Azure DevOps Server: Dev18.M170.6
ServiceNow Change Management Extension: 4.176.1

**Comment by rohit-batra** [comment]
cc @pavanvamsi3

**Comment by pavanvamsi3** [comment]
@shashban This feature is not available currently in Server 2020, what are your thoughts here?

**Comment by pavanvamsi3** [comment]
This was implemented after Server 2020, this will be available in the next Server release.
