### ISSUE TITLE
ServiceNow change management check does not create a change request

### ISSUE THREAD

**Issue by JordanRBG** [microsoft/azure-pipelines-extensions#895]
@shashban @RoopeshNair

There are a couple of main issues with the ServiceNow integrated check against environments (assuming this is the same behaviour for service connections) that makes the extension unusable. The below issues are encountered when attempting to create a new change request in ServiceNow:

1. Both the 'Normal' and 'Standard' change types are not able to be created despite being configured against the check:

![image](https://user-images.githubusercontent.com/37841077/103362816-81116600-4ab1-11eb-99f1-16a37d3db944.png)
![image](https://user-images.githubusercontent.com/37841077/103362826-866eb080-4ab1-11eb-9c8f-5c41c96bde89.png)

The result is a series of timed out entries against the environment. It looks as though Azure DevOps is trying to scan through all the changes in a given ServiceNow instance without actually creating any changes:

![image](https://user-images.githubusercontent.com/37841077/103362972-e49b9380-4ab1-11eb-89e8-ee1e9337de8f.png)

2. When attempting to view the logs for the check, the page is unresponsive and generally does not provide much information. When trying to view an 'Attempt', the scroll bar for the check is to the far right of the window and does not allow you to navigate to the top of the log. This can be seen in the screenshot above.

The configurations above have been working with no issues using the gates within the legacy 'Release' pipelines in Azure DevOps Services; the above is merely an attempt to utilise the YAML version of an existing working configuration.

**Comment by shashban** [comment]
@JordanRBG Can you please report these issues on the developer community 
https://developercommunity.visualstudio.com/content/problem/post.html?space=21

**Comment by JordanRBG** [comment]
@shashban Have raised issue on developer community:

[https://developercommunity.visualstudio.com/content/problem/1298793/servicenow-change-management-check-does-not-create.html](https://developercommunity.visualstudio.com/content/problem/1298793/servicenow-change-management-check-does-not-create.html)

**Comment by shashban** [comment]
Closing this issue. We'll track through the developer community ticket.

**Comment by Jyoti492** [comment]
Any update on the issue as I am also facing the same issue. GET requests are successfull but no POST request going through the plugin.

Task         : ServiceNow Change Management
Description  : Gate on status of new change request or an existing change request in ServiceNow.
Version      : 2.176.0
Author       : Microsoft

2022-04-26T08:33:48.5207980Z GET https://<snow>.service-now.com//api/now/table/change_request?x_mioms_azpipeline_stage_id=60e397b8-1726-56d2-175e-3fe01dde5f37&x_mioms_azpipeline_build_id=39215&x_mioms_azpipeline_stage_attempt=1&sysparm_fields=number,sys_id,correlation_id
				Response Code: OK
				Response: {
  "result": [
    {
      "number": "CHG0116454",
      "sys_id": "034feb3637875700fc98359b34990e57",
      "correlation_id": ""
    },
    {
      "number": "CHG0116457",
      "sys_id": "34fcaf3337c71300fc98359b34990e98",
      "correlation_id": ""
    },
    {
      "number": "CHG0116458",
      "sys_id": "ad103fb337c71300fc98359b34990e11",
      "correlation_id": ""
    },
    {
      "number": "CHG0116459",
      "sys_id": "57853733370b1300fc98359b34990e80",
      "correlation_id": ""
    },
