### ISSUE TITLE
Extravagant permission requirements on storage account

### ISSUE THREAD

**Issue by Timovzl** [microsoft/azure-pipelines-extensions#897]
The extension, at least when performing `terraform init`, performs certain operations that it shouldn't need to, requiring quite a lot of permissions on not just the container, but even the whole storage account.

The problematic operation I'm running into is `listKeys` _on the whole storage account_. This should not be necessary. We have specified the subscription or (as in my case) service connection, the resource group, the storage account, the container, and the blob key (i.e. name). The extension knows _exactly_ what to look for. Listing anything should be unnecessary.

The error message is this (line breaks mine):

```
Failed to get existing workspaces: Error retrieving keys for Storage Account "___":
storage.AccountsClient#ListKeys: Failure responding to request:
StatusCode=403 -- Original Error: autorest/azure: Service returned an error.
Status=403 Code="AuthorizationFailed" Message=
"The client '___' with object id '___' does not have authorization to perform action
'Microsoft.Storage/storageAccounts/listKeys/action' over scope
'/subscriptions/___/resourceGroups/___/providers/Microsoft.Storage/storageAccounts/___' or the scope is invalid.
If access was recently granted, please refresh your credentials."
```

My best guess is that the containers are listed in order to check if the required container exists. I expect that this could instead be achieved by simply accessing the container and handling a response saying it does not exist.

I haven't gotten past this error, but it seems likely that the extension will next perform `listKeys` _on the container itself_. This could present the same problem (even though the scope is less extravagant).

Why is this so problematic, you ask - apart from requiring more permissions than strictly necessary?

As we know, Terraform stores sensitive data in the `tfstate` file. For example, we might pull the database administrator password out of Azure KeyVault (or even generate it on the spot with `random_password`) and create a database resource with that password. Now the password is not just in our well-protected KeyVault, but also in the `tfstate` file in the storage account. This makes it essential to use a well-protected storage account - for example, one that is only accessible to the service connection (through a dedicated app registration).

Such a dedicated storage account tends to live in a different resource group, since the main resource group usually grants team members access to its resources, which we want to avoid. In our case, a storage account managed by administrators does not allow listing all the keys in a container, let alone listing all the containers in the storage account (i.e. other teams' Terraform storage containers)!

Could the extension be improved such that it only performs the operations it strictly needs to?

**Comment by AmrutaKawade** [comment]
@Timovzl Terraform extension itself doesn't check any permissions over storage account.
Extension just executes below command


```
terraform  init
-backend-config=storage_account_name=<redacted>
-backend-config=container_name=<redacted>
-backend-config=key=tf/terraform.tfstate
-backend-config=resource_group_name=<redacted>
-backend-config=arm_subscription_id=<redacted>
-backend-config=arm_tenant_id=***
-backend-config=arm_client_id=***
-backend-config=arm_client_secret=***
```

Terraform needs to have access over azure storage to store state in storage Ref [this](https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage#configure-state-back-end). here access_key is provided in backend configuration.

In extension spn is used to access storage account. So spn needs to have [these](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory#verify-role-assignments) permissions 

**How to give permissions to SPN**

![image](https://user-images.githubusercontent.com/65217380/103510573-85f86000-4e8b-11eb-83d2-36d5664eb1b8.png)

1. Click on `Manage` link next to Azure Subscription
2. Click `Manage Service Principal` which will redirect you to the Application Registration of the Service Principal. Copy the name.
3. Go back and click `Manage service connection roles` which will redirect you to the IAM blade of the Azure Subscription. Here you need to assign a role (`Storage Blob Data Contributor` or `Storage Blob Data Owner`) to the service principal. Use name copied in previous step to search service principal

**Comment by AmrutaKawade** [comment]
Please do try out above solution. Closing this issue. Let me know if it doesn't work we will reopen this issue

**Comment by Timovzl** [comment]
Thanks @AmrutaKawade. I was aware that `Storage Blob Data Contributor` or `Storage Blob Data Owner` were required. Unfortunately, these allow you to do much more than is _technically_ necessary for Terraform to put its state in a specified blob.

The initial issue is that Terraform stores sensitive data in its state file, such as passwords/keys it generates and that we, say, store in Azure Key Vault. Because of this, we created a special storage container _outside of the resource group managed by the Terraform script_, to which practically no one has access, except for the Terraform pipeline. This avoids the creation of a storage container that quietly contains all the secrets that the Key Vault is intended to protect. After all, people are careful about access to a Key Vault - storage accounts, not so much.

However, to provide these access restrictions, the storage account was managed from outside the team, i.e. managed organisation-wide. Because of that, the team providing it preferred to create a _container_ per scenario, not a complete storage _account_.

This is where the real issue lies. Terraform requires a lot of listing permissions that it should not technically need (since we have pointed it exactly at the storage blob it is supposed to use). To the best of my knowledge, these permissions cannot be granted for a single storage container without providing them across the entire storage _account_. This would allow the pipeline to access the sensitive containers of _other teams_.

Since the requirements of Terraform are greater than what it should need, to simply work with a tfstate blob, I thought I'd report that this could be improved. Based on your answer, I suppose I should report it to Terraform (or the AzureRM plugin) directly, right?

**Comment by AmrutaKawade** [comment]
> Thanks @AmrutaKawade. I was aware that `Storage Blob Data Contributor` or `Storage Blob Data Owner` were required. Unfortunately, these allow you to do much more than is _technically_ necessary for Terraform to put its state in a specified blob.
> 
> The initial issue is that Terraform stores sensitive data in its state file, such as passwords/keys it generates and that we, say, store in Azure Key Vault. Because of this, we created a special storage container _outside of the resource group managed by the Terraform script_, to which practically no one has access, except for the Terraform pipeline. This avoids the creation of a storage container that quietly contains all the secrets that the Key Vault is intended to protect. After all, people are careful about access to a Key Vault - storage accounts, not so much.
> 
> However, to provide these access restrictions, the storage account was managed from outside the team, i.e. managed organisation-wide. Because of that, the team providing it preferred to create a _container_ per scenario, not a complete storage _account_.
> 
> This is where the real issue lies. Terraform requires a lot of listing permissions that it should not technically need (since we have pointed it exactly at the storage blob it is supposed to use). To the best of my knowledge, these permissions cannot be granted for a single storage container without providing them across the entire storage _account_. This would allow the pipeline to access the sensitive containers of _other teams_.
> 
> Since the requirements of Terraform are greater than what it should need, to simply work with a tfstate blob, I thought I'd report that this could be improved. Based on your answer, I suppose I should report it to Terraform (or the AzureRM plugin) directly, right?

Yes you are right. we don't check any permissions in extension.

**Comment by julie-ng** [comment]
> This is where the real issue lies. Terraform requires a lot of listing permissions that it should not technically need (since we have pointed it exactly at the storage blob it is supposed to use). To the best of my knowledge, these permissions cannot be granted for a single storage container without providing them across the entire storage _account_. This would allow the pipeline to access the sensitive containers of _other teams_.

@Timovzl  correct, AFAIK, you cannot limit scope to a container (although I wish you could).

I want to make clear that this is a Terraform problem, not Azure. I gave Terraform a SAS token scoped to just the container. However, this error message came back

```
Error: Failed to get existing workspaces: containers.Client#ListBlobs: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthenticationFailed" Message="Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:3f266136-a01e-008c-28d5-e982a0000000\nTime:2021-01-13T17:58:44.1448641Z"
```

This means that the [Terraform Workspaces](https://www.terraform.io/docs/state/workspaces.html) feature is querying for all blobs in the container to see how many "workspaces" it can find. 

I want to achieve the same result you want. But I haven't found a way either and it looks like we would have to go to Terraform/HashiCorp to get an answer.

**Comment by Timovzl** [comment]
Great addition, @julie-ng. Indeed, sounds like we would need to submit a ticket there.

Since the problem is not at all relevant to my current assignment, which I'm quite busy with, I'm not diving into it any deeper right now. Should you create a ticket, I hope that you will link to it from here!

**Comment by raelyard** [comment]
The AzureRM provider can be configured such that it won't use keys to talk to storage. This includes for the azurerm backend. This can be done with `shared_access_key_enabled = false` on the provider. This does make some of the functionality in storage unavailable,
https://github.com/hashicorp/terraform-provider-azurerm/issues/17341#issuecomment-1162907877

It seems to be adequate, though, for running the backend. I think this is the best answer I can find for this problem. listKeys is no longer necessary and access only to a container works.
