### ISSUE TITLE
Run terraform in an DevOps pipeline

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [microsoft/azure-pipelines-extensions#900]
Hi,
I created a IaC Pipeline with terraform and azure devops. In the devops pipeline a added a storage account to store the tfstate file in the blob storage. When I run the pipeline, everything works, all services are created, but a can't find the tfstate file in the storage account. here is the code of the yaml file:
jobs:

    - deployment: deployDev

      continueOnError: false

      environment: 'dev'

      strategy:

        runOnce:

          deploy:

            steps:

              - checkout: self

              - task: TerraformInstaller@0

                displayName: 'install'

                inputs:

                  terraformVersion: '0.12.3'

              - task: TerraformTaskV1@0

                displayName: 'init'

                inputs:

                  provider: 'azurerm'

                  command: 'init'

                  backendServiceArm: ' (XXX)'

                  backendAzureRmResourceGroupName: 'terraform-rg'

                  backendAzureRmStorageAccountName: 'editerraformaccount'

                  backendAzureRmContainerName: 'editerraformcontainer'

                  backendAzureRmKey: 'terraformDev.tfstate'

                  workingDirectory: $(System.DefaultWorkingDirectory)/Terraform/Dev

              - task: TerraformTaskV1@0

                displayName: 'plan'

                inputs:

                  provider: 'azurerm'

                  command: 'plan'

                  #commandOptions: '-input=false'

                  environmentServiceNameAzureRM: ' (XXX)'

                  workingDirectory: $(System.DefaultWorkingDirectory)/Terraform/Dev

              - task: TerraformTaskV1@0

                displayName: 'apply'

                inputs:

                  provider: 'azurerm'

                  command: 'apply'

                  #commandOptions: '-input=false -auto-approve'

                  environmentServiceNameAzureRM: ' (XXX)'

                  workingDirectory: $(System.DefaultWorkingDirectory)/Terraform/Dev

Any ideas?
regards
Andreas

**Comment by julie-ng** [comment]
Does `backendServiceArm` receive the service connection for the **_storage account_** (not the deployment target)?

An error message would be helpful. Personally, I prefer using script, much simpler:

```bash
terraform init \
  -backend-config="storage_account_name=$TF_STATE_BLOB_ACCOUNT_NAME" \
  -backend-config="container_name=$TF_STATE_BLOB_CONTAINER_NAME" \
  -backend-config="key=$TF_STATE_BLOB_FILE" \
  -backend-config="sas_token=$TF_STATE_BLOB_SAS_TOKEN"
```

**Comment by mericstam** [comment]
closed due to inactivity. If you feel this is incorrect please open a new Issue at: https://github.com/microsoft/azure-pipelines-terraform/issues
