### ISSUE TITLE
Support Status of terraform extension

### ISSUE THREAD

**Issue by StefanSchoof** [microsoft/azure-pipelines-extensions#909]
The terraform extensions is getting currently little attention:
 - Last commit was 14 month ago (https://github.com/microsoft/azure-pipelines-extensions/commits/master/Extensions/Terraform/Src)
 - There are 9 open PRs from community and team (https://github.com/microsoft/azure-pipelines-extensions/pulls?q=is%3Apr+is%3Aopen+terraform) and all getting no feedback. The oldest is one year open.
 - From the open issues 54 of 104 have terraform in the title. (https://github.com/microsoft/azure-pipelines-extensions/issues?page=3&q=is%3Aissue+is%3Aopen+terraform)

This smells for me like an abandoned project. Can you please give a status, about the future of the MS terraform Extension. If there is no further work done from MS, we must think about alternatives.

**Comment by makaanneo** [comment]
I as well curious what's the plan for the Terraform extension the other https://github.com/hashicorp/azure-pipelines-extension-terraform looks as well dead to me :(

**Comment by CaptainStealthy** [comment]
Wow, I didn't realize how many open issues are just for the Terraform extension! 😯

Microsoft, if anyone is reading this, you guys don't even have to write any code. Just have a developer review pull requests a few times a week! 😅

**Comment by mericstam** [comment]
Hi, My name is Manuel and a part of Solidify, newly appointed maintainers of Terraform extension. We are working on some reported issues and plan to fix more in the near future. Closing this Issue. Feel free to reopen it if you think this is incorrect.
