### ISSUE TITLE
Terraform Extension Plan and Apply version mismatch

### ISSUE THREAD

**Issue by rick-ha** [microsoft/azure-pipelines-extensions#911]
Hi Team, 

This issue started happening today (had no issues yesterday) - the command "terraform plan -out="xxx.tfplan"" is creating a plan based off of Terraform version 0.14.5, but when the Terraform apply task runs, it is trying to use 0.14.6, thus causing a version mismatch. 

Currently using Microsoft Hosted agent and the Terraform extension by Microsoft Corporation.

Can provide YAML pipeline if needed.

Terraform Plan task as run below:
![image](https://user-images.githubusercontent.com/70251854/107426588-0d1da100-6ae6-11eb-8db9-e785bfbd7c30.png)

Terraform Apply task as run below:
![image](https://user-images.githubusercontent.com/70251854/107426666-232b6180-6ae6-11eb-9eda-9227aa408717.png)

On another note, is it possible to force Azure Pipeline's Terraform task to use a certain version? (without having to use the Terraform installer task)

EDIT: More info - the plan and apply stages are separated by stages, the apply stage downloads the artifact published by the plan stage and runs the .tfplan there.

EDIT2: This seems to happen randomly, but quite occasionally - I have had to re-run my pipeline multiple times and it has been a 50/50. It seems like the hosted agent will have either version.

**Comment by lockdrew** [comment]
This also happening to us except for version 14.6 and 14.7. Seems to resolve the problem when I specify the version of terraform in our code with an "= version" and manually install the terraform version it works just fine. We're using the "Azure Pipelines" hosted agents, so I'm wondering if some of the agents just don't have the same version installed? @rick-ha are you using self-hosted agents?

**Comment by rick-ha** [comment]
> This also happening to us except for version 14.6 and 14.7. Seems to resolve the problem when I specify the version of terraform in our code with an "= version" and manually install the terraform version it works just fine. We're using the "Azure Pipelines" hosted agents, so I'm wondering if some of the agents just don't have the same version installed? @rick-ha are you using self-hosted agents? 

@lockdrew nah I am using Microsoft-hosted agents. I didn't want to have to use the terraform installer if I don't have to (my pipelines to deploy infra via TF are mostly for development and validation purposes anyways). I am curious though, are you outputting a plan as well? I'm theorizing that if I just use auto-approve instead of plan for now, that could be a suitable workaround

**Comment by lockdrew** [comment]
@rick-ha  think that's the same thing? Both are just Microsoft-hosted agents, so I think that this might actually be an issue with azure DevOps rather than the terraform tasks. 

We currently are outputting a plan as an artificat and running it in a different stage. I do think that'd be a suitable workaround for now? I might just switch to using the validate task instead of the plan task if we were to do that - since I just want to have some sort of PR validation built in to our pipeline.

**Comment by rick-ha** [comment]
@lockdrew yeah I had a hunch it would be the agents themselves since it'll work after I rerun the pipeline a few more times.

I haven't tested if terraform inits with one ver and then tries to apply with another ver so that might be another deal :/  

As for your last point with validate, something I did over in GitHub Actions was to do something like "terraform plan -no-color > plan.log" and then have the body of the comment be the contents of the plan so you'd at least get some val there in your PR

**Comment by lockdrew** [comment]
@rick-ha Thanks for the idea! Never thought of doing that. Looks like System.AccessToken works just fine so long as you grant permissions to access the PR. Stackoverflow on it [here](https://stackoverflow.com/questions/60048492/how-to-create-a-comment-in-azure-devops-pr-in-case-of-build-failure).

**Comment by rick-ha** [comment]
@lockdrew glad to hear and thanks for your input as well!

**Comment by artur-carvalho** [comment]
DId you guys found any workaround to fix it? I'm having the same issue.

**Comment by rick-ha** [comment]
@artur-carvalho - I'm not sure if Drew did, but I ended up taking out the creation of a plan and just used a fixtures var-file set to auto-approve. So :

'terraform plan -var-file="xx.tfvars" '
'terraform apply -var-file="xx.tfvars" -auto-approve'

In my case though, I test locally and only need it to deploy infra and then destroy.

**Comment by artur-carvalho** [comment]
I added a step to install the version in every stage and now it is working properly.

**Comment by mericstam** [comment]
closing this due to it seems resolved. If you feel it is incorrect please open a new Issue at: https://github.com/microsoft/azure-pipelines-terraform/issues

**Comment by tteguayco** [comment]
Why is this issue caused? My `plan` task is using version `1.5.6` and my apply task is using `1.5.7`. It ends up in a failure because of the version mismatch.

It would be nice to know why these two tasks use different versions.

**Comment by Neutrino-Sunset** [comment]
Still a problem. Now with versions 1.8.3 and 1.8.4

Why do build agents supposedly deployed using the same vmimage have different versions of software of them? Frankly this just seems incompetent.

**Comment by jdavisclark** [comment]
still an issue for sure. going between 1.9.7 and 1.9.8 randomly in a release pipeline that has a manual review stage between plan and apply
