### ISSUE TITLE
Terraform init stops/breaks

### ISSUE THREAD

**Issue by mukteswarp** [microsoft/azure-pipelines-extensions#945]
Error: The process 'C:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe' failed with exit code 1

**Comment by mericstam** [comment]
Do you still have issues? please provide information on what version of the task (i.e TerraformTaskV1 or TerraformTaskV1 ) you are using.

**Comment by mericstam** [comment]
closing this. feel free to reopen and add more information if you still have issues
