### ISSUE TITLE
default version of terraform is outdated

### ISSUE THREAD

**Issue by wetwicky** [microsoft/azure-pipelines-extensions#972]
currently, hashicorp has released version 1.0.3 and the default version still refers to an older version 0.12.3

may i suggest to also implement a keyword for the parameters 'terraformVersion' like 'latest' to automatically use the latest version available?

i'm refering to the code here https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/Terraform/Src/Tasks/TerraformInstaller/task.json#L25 at line 25

**Comment by mikedizzle** [comment]
Serious, being able to use latest would be huge.

**Comment by mericstam** [comment]
I will look into adding a 'latest' keyword to make the latest version default.
