### ISSUE TITLE
Install latest Terraform version

### ISSUE THREAD

**Issue by coding-domlin** [microsoft/azure-pipelines-extensions#994]
We are using the Terraform Installer Task to install specific Terraform versions. This works without any issues.

Cause of a new requirements we need to install the latest Terraform version every time the task gets executed.

We are not allowed to leave the version field empty, furthermore the task breaks of during execusion when we insert "latest" as value.

How is it possible that the Terraform Installer Task installs the latest version every time it get executed?

We didn't found anything about this usecase in your documentation.

**Comment by mericstam** [comment]
Hi, We will soon release a new version of this task with support for the 'latest' keyword.
